### ISSUE TITLE
Bundle tool "install apks" command isn't working sometimes.

### ISSUE THREAD

**Issue by saurabhkpatel** [google/bundletool#10]
**Describe the bug**
Bundle tool install apks command isn't working `bundletool install-apks --apks=my_app.apks` on Nexus 6P device (Android Oreo) sometimes. Although it doesn't give any problem for Google Pixel 2 XL. 

I tried to run the following the command to get the device specs. but got the following weird output. Do you know what could be the cause of this?

```
$ bundletool get-device-spec --output=nexus6p.json
Warning: Can't detect device locale, will use 'en-US'.

$ cat nexus6p.json
{
  "supportedLocales": ["en-US"],
  "screenDensity": 4294967295,
  "sdkVersion": 1
}%
```

**Bundletool version(s) affected**
Version: [e.g. 0.3.3]

**Stacktrace**
$ bundletool install-apks --apks=my_app.apks
                                                                          
Warning: Can't detect device locale, will use 'en-US'.
[BT:0.3.3] Error: Installation of the app failed.
com.android.tools.build.bundletool.exceptions.InstallationException: Installation of the app failed.
	at com.android.tools.build.bundletool.exceptions.InstallationException$Builder.build(InstallationException.java:47)
	at com.android.tools.build.bundletool.exceptions.InstallationException$Builder.build(InstallationException.java:41)
	at com.android.tools.build.bundletool.device.DdmlibDevice.installApks(DdmlibDevice.java:98)
	at com.android.tools.build.bundletool.device.ApksInstaller.installOnDevice(ApksInstaller.java:89)
	at com.android.tools.build.bundletool.device.ApksInstaller.installApks(ApksInstaller.java:78)
	at com.android.tools.build.bundletool.device.ApksInstaller.installApks(ApksInstaller.java:45)
	at com.android.tools.build.bundletool.commands.InstallApksCommand.lambda$execute$4(InstallApksCommand.java:138)
	at com.android.tools.build.bundletool.io.TempFiles.lambda$withTempDirectory$0(TempFiles.java:67)
	at com.android.tools.build.bundletool.io.TempFiles.withTempDirectoryReturning(TempFiles.java:51)
	at com.android.tools.build.bundletool.io.TempFiles.withTempDirectory(TempFiles.java:70)
	at com.android.tools.build.bundletool.commands.InstallApksCommand.execute(InstallApksCommand.java:122)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:85)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:44)
Caused by: com.android.ddmlib.InstallException: List of APKs is empty: the main APK must be specified.
	at com.android.ddmlib.Device.installPackages(Device.java:930)
	at com.android.tools.build.bundletool.device.DdmlibDevice.installApks(DdmlibDevice.java:92)
	... 10 more
Caused by: java.lang.IllegalArgumentException: List of APKs is empty: the main APK must be specified.
	at com.android.ddmlib.SplitApkInstaller.validateArguments(SplitApkInstaller.java:214)
	at com.android.ddmlib.SplitApkInstaller.create(SplitApkInstaller.java:237)
	at com.android.ddmlib.Device.installPackages(Device.java:925)

**To Reproduce**
Steps to reproduce the behavior.
- Generate the apks set archive.
- install the apk from this apks set.

**Environment:**
OS: MAC OS
Device : Nexus 6p

**Comment by tdobek** [comment]
Hi Saurabh,

Thanks for reporting the issue.

Could you confirm which adb version are you using ?
And by it happening sometimes - do you mean the Nexus 6P issue sometimes goes away?

Tom

**Comment by keyboardsurfer** [comment]
Your screen density and sdk version captured in the nexus6p.json seem to be off for the device in question.

But the main cause for the error is this line: 
> List of APKs is empty: the main APK must be specified.
It seems like you've created an empty .apks file. 
You can check that there's actual apks in the .apks file by unzipping it.

**Comment by saurabhkpatel** [comment]
@tdobek: Yes, It went away after some time, it seems that problem with the command `bundletool get-device-spec`.
Anyways, I'll keep an eye on it and report it later if I face the similar issue.

**Comment by tdobek** [comment]
We've improved the `get-device-spec` error handling in 0.4.2, so whenever this issue reoccurs, you should be notified to retry the command. Closing this issue.

**Comment by gajendrakumartwinwal** [comment]
Getting error:
even i have added ANDROID_HOME in enviourment variables

LOG---
Error: Unable to determine the location of ADB. Please set the --adb flag or define ANDROID_HOME environment variable.
com.android.tools.build.bundletool.exceptions.CommandExecutionException: Unable to determine the location of ADB. Please set the --adb flag or define ANDROID_HOME environment variable.
	at com.android.tools.build.bundletool.commands.InstallApksCommand.lambda$null$1(InstallApksCommand.java:108)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.android.tools.build.bundletool.commands.InstallApksCommand.lambda$fromFlags$2(InstallApksCommand.java:106)
	at java.util.Optional.orElseGet(Optional.java:267)
	at com.android.tools.build.bundletool.commands.InstallApksCommand.fromFlags(InstallApksCommand.java:101)
	at com.android.tools.build.bundletool.commands.InstallApksCommand.fromFlags(InstallApksCommand.java:90)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:87)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:44)

**Comment by gajendrakumartwinwal** [comment]
Getting error:
even i have added ANDROID_HOME in enviourment variables

LOG---

```
> Error: Unable to determine the location of ADB. Please set the --adb flag or define ANDROID_HOME environment variable.
> com.android.tools.build.bundletool.exceptions.CommandExecutionException: Unable to determine the location of ADB. Please set the --adb flag or define ANDROID_HOME environment variable.
> at com.android.tools.build.bundletool.commands.InstallApksCommand.lambda$null$1(InstallApksCommand.java:108)
> at java.util.Optional.orElseThrow(Optional.java:290)
> at com.android.tools.build.bundletool.commands.InstallApksCommand.lambda$fromFlags$2(InstallApksCommand.java:106)
> at java.util.Optional.orElseGet(Optional.java:267)
> at com.android.tools.build.bundletool.commands.InstallApksCommand.fromFlags(InstallApksCommand.java:101)
> at com.android.tools.build.bundletool.commands.InstallApksCommand.fromFlags(InstallApksCommand.java:90)
> at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:87)
> at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:44)
```

**Comment by plecesne** [comment]
Is `adb` present in your `ANDROID_HOME` directory under `platform-tools`? Also, is it executable?

**Comment by gajendrakumartwinwal** [comment]
Yes it is presented in platform-tools and even i am able to run command
adb devices

Which is working fine

But when i use this with bundletool it does not work.
**See the screenshot**
<img width="1021" alt="screen shot 2018-10-04 at 5 31 55 pm" src="https://user-images.githubusercontent.com/9496478/46472666-852f7a00-c7fb-11e8-8eba-63aa9d0c4473.png">

**Comment by plecesne** [comment]
Does running `$ANDROID_HOME/platform-tools/adb devices` also work?

**Comment by plecesne** [comment]
The ANDROID_HOME variable should be set to the path to the _root_ of the Android SDK, not platform-tools or any of the other subdirectories.
