### ISSUE TITLE
bundletool install-apks exception " No connected devices found."

### ISSUE THREAD

**Issue by JachinGao** [google/bundletool#11]
I have compiled apks through ‘build-apks’ command . But when I start to install apks, it will report error-No connected devices found. 

 I can find my device through the adb command. So i don’t know what causes this.

![default](https://user-images.githubusercontent.com/20591711/40423601-ae677d0e-5ec5-11e8-80ca-a948387c8e9c.PNG)

![2](https://user-images.githubusercontent.com/20591711/40423764-1549ce00-5ec6-11e8-8476-6e65d301e628.PNG)

**Comment by plecesne** [comment]
Is the version of `adb` you run the same as the one in your `ANDROID_HOME` environment variable?

**Comment by DilerxD** [comment]
Hi, i have the same problem when i use the command bundletool install-apks dont detect the emulator from android studio 
`java -jar bundletool-all-0.4.1.jar  install-apks --apks=/home/android/Documents/backup/AndroidAppBundleExample/app/release/bundle.apks 
[BT:0.4.1] Error: No connected devices found.
com.android.tools.build.bundletool.exceptions.CommandExecutionException: No connected devices found.
	at com.android.tools.build.bundletool.device.DeviceAnalyzer.getTargetDevice(DeviceAnalyzer.java:116)
	at com.android.tools.build.bundletool.device.DeviceAnalyzer.getAndValidateDevice(DeviceAnalyzer.java:91)
	at com.android.tools.build.bundletool.device.DeviceAnalyzer.getDeviceSpec(DeviceAnalyzer.java:50)
	at com.android.tools.build.bundletool.commands.InstallApksCommand.lambda$execute$3(InstallApksCommand.java:131)
	at com.android.tools.build.bundletool.io.TempFiles.lambda$withTempDirectory$0(TempFiles.java:67)
	at com.android.tools.build.bundletool.io.TempFiles.withTempDirectoryReturning(TempFiles.java:51)
	at com.android.tools.build.bundletool.io.TempFiles.withTempDirectory(TempFiles.java:70)
	at com.android.tools.build.bundletool.commands.InstallApksCommand.execute(InstallApksCommand.java:129)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:85)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:44)`

I'm trying 2 days to fix this error :'(

**Comment by DilerxD** [comment]
Hi, i have a temporary solution, put adb kill-server and then
`java -jar bundletool-all-0.4.1.jar install-apks --apks=/your/apks/directory.apks `

**Comment by walkingice** [comment]
My config
* Mac 10.11.6
* Android Debug Bridge version 1.0.39, Version 0.0.1-4500957
* Java(TM) SE Runtime Environment (build 1.8.0_112-b16)

I got the same problem, and my conclusion is same as @BorisShir . ddmlib's DeviceMonitor starts a new thread[1] to monitor device changes to update its devices list `mDevices`. `getDevices` might get zero device until the list initialized.

[1] https://github.com/JetBrains/adt-tools-base/blob/e5faa7ab0f000cee3de4673250585d277c6ec929/ddmlib/src/main/java/com/android/ddmlib/DeviceMonitor.java#L99

**Comment by tdobek** [comment]
Hi,

Thanks for reporting the issue. We managed to fix it in the meantime (the issue was with not using the hasInitialDeviceList), we will be releasing the next version next week and this should fix it.

**Comment by tdobek** [comment]
The 0.4.2 version is now released. Please let us know if you're experiencing this issue anymore.
