### ISSUE TITLE
NoSuchFileException when paths contain a tilde sign (~)

### ISSUE THREAD

**Issue by baole** [google/bundletool#12]
**Describe the bug**
NoSuchFileException thrown when runs build-apks command

**Bundletool version(s) affected**
Version: [e.g. 0.4.1]

**Stacktrace**
```
macbook-pro:bin$ java -jar bundletool-all-0.4.1.jar build-apks  --bundle=../../app/build/outputs/bundle/playRelease/bundle.aab --output=~/Downloads/tandem.apks
WARNING: The APKs won't be signed and thus not installable unless you also pass a keystore via the flag --ks. See the command help for more information.
[BT:0.4.1] Error: Error while writing the APK Set archive to '~/Downloads/tandem.apks'.
com.android.tools.build.bundletool.exceptions.CommandExecutionException: Error while writing the APK Set archive to '~/Downloads/tandem.apks'.
        at com.android.tools.build.bundletool.exceptions.CommandExecutionException$Builder.build(CommandExecutionException.java:81)
        at com.android.tools.build.bundletool.io.ApkSetBuilderFactory$ApkSetArchiveBuilder.writeTo(ApkSetBuilderFactory.java:124)
        at com.android.tools.build.bundletool.commands.BuildApksCommand.executeWithTempDir(BuildApksCommand.java:310)
        at com.android.tools.build.bundletool.io.TempFiles.withTempDirectoryReturning(TempFiles.java:51)
        at com.android.tools.build.bundletool.commands.BuildApksCommand.execute(BuildApksCommand.java:237)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:72)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:44)
Caused by: java.nio.file.NoSuchFileException: /var/folders/3j/8k6z66l50dq_d1sjfxl8cphh0000gn/T/ZipBuilder-3573363741609217405.zip.tmp -> ~/Downloads/tandem.apks
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:457)
        at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
        at java.nio.file.Files.move(Files.java:1395)
        at com.android.tools.build.bundletool.io.ZipBuilder.writeTo(ZipBuilder.java:105)
        at com.android.tools.build.bundletool.io.ApkSetBuilderFactory$ApkSetArchiveBuilder.writeTo(ApkSetBuilderFactory.java:119)
        ... 5 more
```

**To Reproduce**

**Expected behavior**
Generated .apks file

**Known workaround**

**Environment:**
Mac OS

**Additional context**

**Comment by keyboardsurfer** [comment]
You'll have to pass in a keystore using the `--ks` flag.

**Comment by plecesne** [comment]
You'll need to replace the "~" with the full path to your home directory. We'll try to fix this in a future release.

**Comment by baole** [comment]
Thanks @plecesne. It works
