### ISSUE TITLE
Issue when creating apks file using device spec json

### ISSUE THREAD

**Issue by sajadj313** [google/bundletool#120]
**Description**
Using get-device-spec command, I generated a json file for my device in Windows and transferred it to my Mac for the bundletool build-apks command and it fails.

**Bundle tool versions**
0.10.3 (both Windows and Mac)

Stacktrace
```
INFO: The APKs will be signed with the debug keystore found at '/Users/sajad/.android/debug.keystore'.
[BT:0.10.3] Error: Error while reading the device spec file '/galaxy-j7-pro.json'.
java.io.UncheckedIOException: Error while reading the device spec file '/galaxy-j7-pro.json'.
	at com.android.tools.build.bundletool.device.DeviceSpecParser.parseDeviceSpecInternal(DeviceSpecParser.java:66)
	at com.android.tools.build.bundletool.device.DeviceSpecParser.parseDeviceSpec(DeviceSpecParser.java:39)
	at java.util.Optional.map(Optional.java:215)
	at com.android.tools.build.bundletool.commands.BuildApksCommand.fromFlags(BuildApksCommand.java:510)
	at com.android.tools.build.bundletool.commands.BuildApksCommand.fromFlags(BuildApksCommand.java:409)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:74)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:46)
Caused by: java.nio.file.NoSuchFileException: /galaxy-j7-pro.json
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at java.nio.file.Files.newBufferedReader(Files.java:2784)
	at com.android.tools.build.bundletool.model.utils.files.BufferedIo.reader(BufferedIo.java:49)
	at com.android.tools.build.bundletool.device.DeviceSpecParser.parseDeviceSpecInternal(DeviceSpecParser.java:62)
	... 6 more
```

**Expected behavior** 
Bundle tool should take the aab and json and produce the apks file.

**Environment**
OS: Mac OS 10.14.6
OS: Windows 8.1
Java version: 1.8.0_191

**Comment by plecesne** [comment]
Per the error message `NoSuchFileException: /galaxy-j7-pro.json`, it looks like you put a `/` in front of the file which will search it at the root of your computer, which I imagine is not where the file is.
