### ISSUE TITLE
connected device flag is not working

### ISSUE THREAD

**Issue by ajay-aravind** [google/bundletool#126]
java -jar bundletool-all-0.3.3.jar build-apks --connected-device --bundle=*****.aab --output=nexus.apks

WARNING: The APKs won't be signed and thus not installable unless you also pass a keystore via the flag --ks. See the command help for more information.
[BT:0.3.3] Error: Unrecognized flags: --connected-device
com.android.tools.build.bundletool.utils.flags.ParsedFlags$UnknownFlagsException: Unrecognized flags: --connected-device
        at com.android.tools.build.bundletool.utils.flags.ParsedFlags.checkNoUnknownFlags(ParsedFlags.java:90)
        at com.android.tools.build.bundletool.commands.BuildApksCommand.fromFlags(BuildApksCommand.java:239)
        at com.android.tools.build.bundletool.commands.BuildApksCommand.fromFlags(BuildApksCommand.java:191)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:72)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:44)

Getting this exception.

**Comment by plecesne** [comment]
Per https://github.com/google/bundletool/releases/tag/0.4.2, this flag was added only in version 0.4.2. I recommend you upgrade to use the latest version.
