### ISSUE TITLE
Error: java.lang.IllegalStateException: Did not write as much data as expected

### ISSUE THREAD

**Issue by PaulVrugt** [google/bundletool#136]
**Describe the bug**
Error using bundletool in azure pipeline, running the same command on the build machine via the command line works fine

**Bundletool version(s) affected**
Version: 0.11.0

**Stacktrace**
<details>
<summary>click to open</summary>

```

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/C:/iProvaBuildAgent/_work/79/s/bundletool/bundletool-all-0.11.0.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[BT:0.11.0] Error: java.lang.IllegalStateException: Did not write as much data as expected.
java.lang.RuntimeException: java.lang.IllegalStateException: Did not write as much data as expected.
	at com.android.tools.build.bundletool.io.ConcurrencyUtils.waitFor(ConcurrencyUtils.java:59)
	at com.android.tools.build.bundletool.io.ConcurrencyUtils.waitForAll(ConcurrencyUtils.java:42)
	at java.base/java.util.function.Function.lambda$andThen$1(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at com.android.tools.build.bundletool.io.ApkSerializerManager.serializeApks(ApkSerializerManager.java:180)
	at com.android.tools.build.bundletool.io.ApkSerializerManager.populateApkSetBuilder(ApkSerializerManager.java:101)
	at com.android.tools.build.bundletool.commands.BuildApksManager.executeWithZip(BuildApksManager.java:235)
	at com.android.tools.build.bundletool.commands.BuildApksManager.execute(BuildApksManager.java:116)
	at com.android.tools.build.bundletool.commands.BuildApksCommand.execute(BuildApksCommand.java:532)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:74)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:46)
	Suppressed: java.io.UncheckedIOException: java.nio.file.FileSystemException: C:\Users\BUILDM~1\AppData\Local\Temp\7681746313439209622: failed to delete one or more files; see suppressed exceptions for details
		at com.android.tools.build.bundletool.io.TempDirectory.close(TempDirectory.java:59)
		at com.android.tools.build.bundletool.commands.BuildApksCommand.execute(BuildApksCommand.java:533)
		... 2 more
	Caused by: java.nio.file.FileSystemException: C:\Users\BUILDM~1\AppData\Local\Temp\7681746313439209622: failed to delete one or more files; see suppressed exceptions for details
		at com.google.common.io.MoreFiles.throwDeleteFailed(MoreFiles.java:791)
		at com.google.common.io.MoreFiles.deleteRecursively(MoreFiles.java:537)
		at com.android.tools.build.bundletool.io.TempDirectory.close(TempDirectory.java:57)
		... 3 more
		Suppressed: java.nio.file.DirectoryNotEmptyException: C:\Users\BUILDM~1\AppData\Local\Temp\7681746313439209622
			at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
			at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(Unknown Source)
			at java.base/java.nio.file.Files.delete(Unknown Source)
			at com.google.common.io.MoreFiles.deleteRecursivelyInsecure(MoreFiles.java:665)
			at com.google.common.io.MoreFiles.deleteRecursively(MoreFiles.java:526)
			... 4 more
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Did not write as much data as expected.
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:502)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:461)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:83)
	at com.android.tools.build.bundletool.io.ConcurrencyUtils.waitFor(ConcurrencyUtils.java:49)
	... 10 more
Caused by: java.lang.IllegalStateException: Did not write as much data as expected.
	at com.google.protobuf.CodedOutputStream.checkNoSpaceLeft(CodedOutputStream.java:973)
	at com.google.protobuf.AbstractMessageLite.toByteArray(AbstractMessageLite.java:73)
	at com.android.tools.build.bundletool.io.ZipBuilder.lambda$addFileWithProtoContent$1(ZipBuilder.java:147)
	at com.android.tools.build.bundletool.io.ZipBuilder.writeTo(ZipBuilder.java:101)
	at com.android.tools.build.bundletool.io.ApkSerializerHelper.writeProtoApk(ApkSerializerHelper.java:286)
	at com.android.tools.build.bundletool.io.ApkSerializerHelper.writeToZipFile(ApkSerializerHelper.java:157)
	at com.android.tools.build.bundletool.io.ApkSerializerHelper.writeToZipFile(ApkSerializerHelper.java:146)
	at com.android.tools.build.bundletool.io.StandaloneApkSerializer.writeToDiskInternal(StandaloneApkSerializer.java:88)
	at com.android.tools.build.bundletool.io.StandaloneApkSerializer.writeToDisk(StandaloneApkSerializer.java:57)
	at com.android.tools.build.bundletool.io.ApkSetBuilderFactory$ApkSetArchiveBuilder.addStandaloneApk(ApkSetBuilderFactory.java:128)
	at com.android.tools.build.bundletool.io.ApkSerializerManager$ApkSerializer.serialize(ApkSerializerManager.java:392)
	at com.android.tools.build.bundletool.io.ApkSerializerManager.lambda$null$3(ApkSerializerManager.java:184)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:117)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:38)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)


```
</details>

**To Reproduce**
We ran the following command during the pipeline:
java -jar bundletool-all-0.11.0.jar build-apks --bundle="<ourbundle>.aab" --output="<output>.apks" --ks="<path to keystore>" --ks-key-alias="<alias>" --ks-pass=pass:<password>

**Expected behavior**
I expect that the apks file is generated. When running the command on the server running the build, it works, however, when running it during the build process, the error in the stacktrace is shown

**Known workaround**
Running the command manually

**Environment:**
OS: Windows server 2012

**Additional context**
I don't really think this is a bug, but an issue the occurs during a specific context the command is run in. I'm looking for the reason this issue occurs, so we can circumvent it.

**Comment by ymakhno** [comment]
Should be fixed in 0.13.3. Looks similar to #61.
