### ISSUE TITLE
wso2 getting NullPointer exception for /api/device-mgt/android/mssl/v1.0/configuration/.

### ISSUE THREAD

**Issue by sumit1dec** [google/bundletool#156]
This API seems to be throwing NullPointer Exception WSO2 IOT Server 3.3.0:

TID: [-1234] [] [2020-04-15 09:05:28,421] ERROR {org.apache.synapse.transport.passthru.ServerWorker} -  Error processing GET request for : /api/device-mgt/android/mssl/v1.0/configuration/. Error detail: null.  {org.apache.synapse.transport.passthru.ServerWorker}
java.lang.NullPointerException
        at org.wso2.carbon.apimgt.handlers.AuthenticationHandler.handleRequest(AuthenticationHandler.java:150)
        at org.apache.synapse.rest.API.process(API.java:325)
        at org.apache.synapse.rest.RESTRequestHandler.apiProcess(RESTRequestHandler.java:123)
        at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:101)
        at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:69)
        at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:303)
        at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:92)
        at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
        at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:337)
        at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:158)
        at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by plecesne** [comment]
You seem to be having the wrong project.
There is nothing in that stacktrace that contains "bundletool"
