### ISSUE TITLE
OutOfMemoryError when building APKs for local testing

### ISSUE THREAD

**Issue by PhilippeStoffel** [google/bundletool#159]
**Describe the bug**
Generating APKs with the `--local-testing` end with a OutOfMemoryError exception.

**Bundletool version(s) affected**
Version: 0.14.0

**Stacktrace**
```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Unknown Source)
        at java.io.ByteArrayOutputStream.toByteArray(Unknown Source)
        at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:167)
        at com.android.tools.build.bundletool.io.ZipBuilder.writeTo(ZipBuilder.java:92)
        at com.android.tools.build.bundletool.io.ApkSetBuilderFactory$ApkSetArchiveBuilder.writeTo(ApkSetBuilderFactory.java:173)
        at com.android.tools.build.bundletool.commands.BuildApksManager.executeWithZip(BuildApksManager.java:261)
        at com.android.tools.build.bundletool.commands.BuildApksManager.execute(BuildApksManager.java:123)
        at com.android.tools.build.bundletool.commands.BuildApksCommand.execute(BuildApksCommand.java:523)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:75)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:47)
```

**To Reproduce**
Download the latest bundletool release build, and try to build APKs with the following command.
`java -jar bundletool-all.jar build-apks --bundle=path/to/your/bundle.aab --output=output.apks --local-testing`

**Expected behavior**
Bundletool should produce a file called `output.apks`

**Known workaround**
Add the java argument `-Xmx1g` to increase the maximum heap size.

**Environment:**
OS: Windows 10 Professional version 10.0.17763 number 17763
CPU: Intel i7-7700K
Memory: 16 GB

**Additional context**
Bundle size: 480 MB
The result is the same without the `--local-testing` argument.

**Comment by ymakhno** [comment]
From my point of view solution with increasing JVM heap size via providing `-Xmx` flag is a correct one and already provided in **Known workaround** section. Why do you not satisfy with it?

**Comment by ymakhno** [comment]
Closing as correct solution is provided.

**Comment by bhushang098** [comment]
I Am Running command 
java -jar "bundletool-all-1.4.0.jar" build-apks --bundle="app-debug.aab" --output="gotapp.apks" --Xmx =1024

it says  Unrecognized flags: --Xmx

**Comment by plecesne** [comment]
```
java -Xmx:1024M -jar ...
```

See https://docs.oracle.com/cd/E13150_01/jrockit_jvm/jrockit/jrdocs/refman/optionX.html
