### ISSUE TITLE
Error while writing the APK Set archive

### ISSUE THREAD

**Issue by yperess** [google/bundletool#16]
**Describe the bug**
I get an error `java.nio.file.NoSuchFileException` when trying to build the `.apks` file. The command I'm using is:
```
bundletool build-apks --bundle=/home/yperess/workspace/myapp/app/build/outputs/bundle/release/bundle.aab --output=/home/yperess/workspace/myapp/build/outputs/apk/release/myapp.apks --ks=/home/yperes/keystores/org.jks --ks-pass=pass:password --ks-key-alias=MyApp --key-pass=pass:password
```

**Bundletool version(s) affected**
Version: 0.4.1

**Stacktrace**
```
[BT:0.4.1] Error: Error while writing the APK Set archive to '/home/yperess/workspace/myapp/build/outputs/apk/release/myapp.apks'.
com.android.tools.build.bundletool.exceptions.CommandExecutionException: Error while writing the APK Set archive to '/home/yperess/workspace/myapp/build/outputs/apk/release/myapp.apks'.
	at com.android.tools.build.bundletool.exceptions.CommandExecutionException$Builder.build(CommandExecutionException.java:81)
	at com.android.tools.build.bundletool.io.ApkSetBuilderFactory$ApkSetArchiveBuilder.writeTo(ApkSetBuilderFactory.java:124)
	at com.android.tools.build.bundletool.commands.BuildApksCommand.executeWithTempDir(BuildApksCommand.java:310)
	at com.android.tools.build.bundletool.io.TempFiles.withTempDirectoryReturning(TempFiles.java:51)
	at com.android.tools.build.bundletool.commands.BuildApksCommand.execute(BuildApksCommand.java:237)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:72)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:44)
Caused by: java.nio.file.NoSuchFileException: /tmp/ZipBuilder-6188385578339465164.zip.tmp -> /home/yperess/workspace/myapp/build/outputs/apk/release/myapp.apks
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:457)
	at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
	at java.nio.file.Files.move(Files.java:1395)
	at com.android.tools.build.bundletool.io.ZipBuilder.writeTo(ZipBuilder.java:105)
	at com.android.tools.build.bundletool.io.ApkSetBuilderFactory$ApkSetArchiveBuilder.writeTo(ApkSetBuilderFactory.java:119)
	... 5 more
```

**To Reproduce**
```
bundletool build-apks --bundle=/home/yperess/workspace/myapp/app/build/outputs/bundle/release/bundle.aab --output=/home/yperess/workspace/myapp/build/outputs/apk/release/myapp.apks --ks=/home/yperes/keystores/org.jks --ks-pass=pass:password --ks-key-alias=MyApp --key-pass=pass:password
```

**Expected behavior**
Generate a `.apks` file

**Known workaround**
If you have found a workaround, please specify what it is.

**Environment:**
OS: Ubuntu 18.04

**Additional context**

**Comment by kvafy** [comment]
Thank you for reporting this issue.

Bundletool uses temporary files to store intermediate results, so it is possible that the OS performed a clean-up during bundletool execution. Is this a persistent issue or a one-off? Is the system possibly low on disk space?

**Comment by yperess** [comment]
This happens 100% of the time

**Comment by plecesne** [comment]
I believe the issue is that the directory `/home/yperess/workspace/myapp/build/outputs/apk/release/` does not exist, so `bundletool` is unable to write the file there.
Could you confirm?

**Comment by CliffBurton** [comment]
> I believe the issue is that the directory `/home/yperess/workspace/myapp/build/outputs/apk/release/` does not exist, so `bundletool` is unable to write the file there.
> Could you confirm?

@plecesne I had the same issue reported by @yperess and I just want to confirm fixing the path in the `--output` flag made the command to compile and my `.apks` has been generated.
My mistake was thinking that writing an unexisting folder in the `--output` flag would automatically create that folder for me.

**Comment by plecesne** [comment]
Note that this will be fixed in next version of bundletool.

**Comment by tutipeti** [comment]
Sorry for reviving an old issue - @plecesne could you please confirm that this has indeed been fixed? It seems I'm having the same problem right now with version 1.2.0.

Bundletool failed on our CI but was working fine for me locally, and the only difference I see between the two is that the parent folder doesn't exist yet on CI.

**Comment by ymakhno** [comment]
Yes, it should be fixed already and if output directory doesn't exist you should see in logs the following message "Output directory ... does not exist, creating it." 

https://github.com/google/bundletool/blob/master/src/main/java/com/android/tools/build/bundletool/commands/BuildApksCommand.java#L650

**Comment by tutipeti** [comment]
@ymakhno thanks a lot! You made me realise that I'm hijacking the wrong issue here. Bundletool failed for me when creating the aab, not when building the apks. :(
