### ISSUE TITLE
Error: Installation of the app failed on bundletool install-apks command

### ISSUE THREAD

**Issue by renatopeterman** [google/bundletool#17]
**Describe the bug**
Hi! I'm trying to install the `.apks` on my Nexus 6P but I'm getting `[BT:0.4.1] Error: Installation of the app failed.` 100% of the time, but when I try to install on my Asus Zenfone Go it works. I tried signing with release keys, debug keys, building from command line and Android Studio but no success. I have some native/cpp code in my app and I got this abi related error once: `E/SplitApkInstaller: Failed to finalize session : INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113`, weird that this error just showed up once.

**Bundletool version(s) affected**
Version: 0.4.1

**Stacktrace**
```java
[BT:0.4.1] Error: Installation of the app failed.
com.android.tools.build.bundletool.exceptions.InstallationException: Installation of the app failed.
	at com.android.tools.build.bundletool.exceptions.InstallationException$Builder.build(InstallationException.java:47)
	at com.android.tools.build.bundletool.exceptions.InstallationException$Builder.build(InstallationException.java:41)
	at com.android.tools.build.bundletool.device.DdmlibDevice.installApks(DdmlibDevice.java:98)
	at com.android.tools.build.bundletool.device.ApksInstaller.installOnDevice(ApksInstaller.java:89)
	at com.android.tools.build.bundletool.device.ApksInstaller.installApks(ApksInstaller.java:78)
	at com.android.tools.build.bundletool.device.ApksInstaller.installApks(ApksInstaller.java:45)
	at com.android.tools.build.bundletool.commands.InstallApksCommand.lambda$execute$3(InstallApksCommand.java:145)
	at com.android.tools.build.bundletool.io.TempFiles.lambda$withTempDirectory$0(TempFiles.java:67)
	at com.android.tools.build.bundletool.io.TempFiles.withTempDirectoryReturning(TempFiles.java:51)
	at com.android.tools.build.bundletool.io.TempFiles.withTempDirectory(TempFiles.java:70)
	at com.android.tools.build.bundletool.commands.InstallApksCommand.execute(InstallApksCommand.java:129)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:85)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:44)
Caused by: com.android.ddmlib.InstallException
	at com.android.ddmlib.SplitApkInstaller.install(SplitApkInstaller.java:100)
	at com.android.ddmlib.Device.installPackages(Device.java:926)
	at com.android.tools.build.bundletool.device.DdmlibDevice.installApks(DdmlibDevice.java:92)
	... 10 more
Caused by: com.android.ddmlib.ShellCommandUnresponsiveException
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:557)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:383)
	at com.android.ddmlib.Device.executeShellCommand(Device.java:573)
	at com.android.ddmlib.SplitApkInstaller.install(SplitApkInstaller.java:86)
	... 12 more
```

**To Reproduce**
```
./gradlew clean cleanBuildCache bundleRelease
java -jar bundletool.jar build-apks --bundle=./bundle.aab --output=./my_app.apks --ks=./release.keystore --ks-pass=pass:[pass] --ks-key-alias=[alias] --key-pass=pass:[pass]
java -jar bundletool.jar install-apks --apks=./my_app.apks
```

**Expected behavior**
I expect the app to be installed in my Nexus 6P like it does for the Asus Zenfone go.

**Environment:**
OS: macOS high sierra 10.13.4

**Comment by mufumbo** [comment]
+1

**Comment by plecesne** [comment]
For the users not being able to install, please contact the [Play Console support team](https://support.google.com/googleplay/android-developer/?hl=en-GB#topic=3450769&contact=1) (see "Send feedback & report bugs") since they can request more details about your app in private and investigate more in depth.

Regarding the `install-apks` command, this is indeed very curious. Did the `adb devices` command show the device connected? If so, could you attach the file `toc.pb` in the APK Set archive? (`unzip cooking.apks toc.pb` should do to extract it).

**Comment by renatopeterman** [comment]
Ok. Yes, it's showing up in the devices list: 

![screenshot 2018-06-05 15 27 42](https://user-images.githubusercontent.com/2411367/40995277-09311ff6-68d5-11e8-9680-cc8da73c0ca4.png)

Here's the `toc.pb` file:

[toc.pb.zip](https://github.com/google/bundletool/files/2073538/toc.pb.zip)

**Comment by mufumbo** [comment]
This issue is impacting the releases for me too. Whenever I release a bundle, I can't seem to install it on my pixel2 phone through the play store. Hope anyone can fix this before all developers start using this tool. I don't think google used this tool for their own apps?

**Comment by renatopeterman** [comment]
Hi @plecesne 
I think I figure out the problem.
We have some native code and I was specifying the following abiFilters:

```groovy
ndk {
    abiFilters 'x86', 'x86_64', 'armeabi-v7a', 'arm64-v8a'
}
```

I just removed `arm64-v8a` and now I'm able to install with no problem. Still not sure why, maybe our native code is not arm64 ready. 
The final `abiFilters` values are now:

```groovy
ndk {
    abiFilters 'x86', 'x86_64', 'armeabi-v7a'
}
```

I'll try on more devices to make sure that it's really working.

**Comment by plecesne** [comment]
@renatopeterman Thanks for the update. Did you have any libraries under the "base/lib/arm64-v8" directory in your App Bundle when you still had `abiFilters [...], 'arm64-v8a'` ?

**Comment by renatopeterman** [comment]
Yes, there is a few files there, but both `arm64-v8a` and `x86_64` are missing the lib `librs.rotator.so`, but not sure if it's related. 

![screenshot 2018-06-06 08 35 14](https://user-images.githubusercontent.com/2411367/41035916-9a5a4496-6964-11e8-830a-47f37988b180.png)

![screenshot 2018-06-06 08 36 03](https://user-images.githubusercontent.com/2411367/41035938-abbd3ffe-6964-11e8-83f0-073692d25136.png)

**Comment by plecesne** [comment]
Nothing obvious jumps to mind. I think this will require a deeper investigation with the actual files at hand. If you don't want to share them publicly on this thread, I would recommend you to contact the [Play Console support team](https://support.google.com/googleplay/android-developer/?hl=en-GB#topic=3450769&contact=1) (see "Send feedback & report bugs") and provide them with an explanation of the issue, the App Bundle causing trouble, and a link to this thread.

**Comment by renatopeterman** [comment]
Ok! Thanks for your help! We'll contact the support team to try to understand this.

**Comment by hegazy** [comment]
The same 507 error!

**Comment by mochadwi** [comment]
For those having the same error. Might wanna try this approach:

```
bundletool build-apks --connected-device --bundle="your-aab.aab" --output="your-app.apks"
```

the `--connected-device` param will only build the specific API for your connected device. I happened to forgot to add this param and resulting in a bigger apk size, also the apk result can't be installed on any devices and throws this error.

**Comment by rpattabi** [comment]
> Ok! Thanks for your help! We'll contact the support team to try to understand this.

@renatopeterman Were you able to resolve this problem? I don't face this problem, but installing through bundle makes my native libs disappear and I suspect this might be related.

**Comment by plecesne** [comment]
@rpattabi Please file a separate bug. Most likely your issue is unrelated.
