### ISSUE TITLE
Failed to generate apks from android bundle file.

### ISSUE THREAD

**Issue by doniwinata0309** [google/bundletool#178]
**Bundletool version(s) affected**
Version: 1.2.0

**Stacktrace**
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at com.android.tools.build.bundletool.model.ManifestDeliveryElement.lambda$null$1(ManifestDeliveryElement.java:135)
	at java.util.Optional.map(Optional.java:215)
	at com.android.tools.build.bundletool.model.ManifestDeliveryElement.lambda$getInstallTimeRemovableValue$2(ManifestDeliveryElement.java:130)
	at java.util.Optional.flatMap(Optional.java:241)
	at com.android.tools.build.bundletool.model.ManifestDeliveryElement.getInstallTimeRemovableValue(ManifestDeliveryElement.java:126)
	at com.android.tools.build.bundletool.model.ManifestDeliveryElement.isInstallTimeRemovable(ManifestDeliveryElement.java:112)
	at com.android.tools.build.bundletool.mergers.BundleModuleMerger.lambda$shouldMerge$2(BundleModuleMerger.java:119)
	at java.util.Optional.map(Optional.java:215)
	at com.android.tools.build.bundletool.mergers.BundleModuleMerger.shouldMerge(BundleModuleMerger.java:109)
	at com.android.tools.build.bundletool.mergers.BundleModuleMerger.lambda$mergeNonRemovableInstallTimeModules$0(BundleModuleMerger.java:66)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:313)
	at com.google.common.collect.CollectSpliterators$1WithCharacteristics.forEachRemaining(CollectSpliterators.java:65)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:313)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at com.android.tools.build.bundletool.mergers.BundleModuleMerger.mergeNonRemovableInstallTimeModules(BundleModuleMerger.java:68)
	at com.android.tools.build.bundletool.commands.BuildApksManager.execute(BuildApksManager.java:133)
	at com.android.tools.build.bundletool.commands.BuildApksCommand.execute(BuildApksCommand.java:624)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:75)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:47)
MacBook-Pro:android-v3 doni.winata$ 
**To Reproduce**
java -jar ./bundletool-all-1.2.0.jar build-apks --bundle=path_to_fileaab  --output=./newes2.apks  --connected-device

This only happen for our recent aab build but working perfectly on old bundle file. Both of them using the same AGP version. Any clues what might be wrong ? 

Thanks

**Comment by plecesne** [comment]
Do you have 

```
<dist:install-time>
   <dist:removable>
</dist:install-time>
```

in your manifest?

If so, also add the `value` attribute in the `removable` element:

```
<dist:install-time>
   <dist:removable value="true">
</dist:install-time>
```

Hopefully that unblocks you until we fix the error message.

**Comment by plecesne** [comment]
Actually, the issue might be that the `dist:` namespace is not set on the "value" attribute, as the documentation doesn't have it either. I'll get the documentation fixed.

**Comment by doniwinata0309** [comment]
Yes recently we add this code on our DFM module:

            <dist:install-time>
                <dist:removable value="false"/>
            </dist:install-time>

So do you mean it should be changed into this ?

<dist:install-time>
    <dist:removable dist:value="false"/>
</dist:install-time>

**Comment by doniwinata0309** [comment]
I will check it in a moment, actually this only happen for connected device, but generating universal apk working fine. By the way, is it also causing issue when we uploaded this bundle to Playstore  or it is only issue when using bundletool manually ?

**Comment by plecesne** [comment]
Yes, that's how you should change it.

Yes, this will also cause an issue when uploading to Play Store.

**Comment by doniwinata0309** [comment]
It is working now, thanks for your advice. I will close this issue.
