### ISSUE TITLE
Duplicate assets in asset modules no longer permitted.

### ISSUE THREAD

**Issue by simon-bond** [google/bundletool#181]
**Describe the bug**
As of v1.2.0, duplicate assets are no longer permitted.

I can see that this behaviour has been changed because resources in asset modules are uncompressed, whereas in features modules these are compressed. Can this check in bundletool only reject a collision where a clash occurs between an asset module and a feature module? It seems to me that if this resource only exists in asset modules, then there is no ambiguity between compressed or uncompressed. Please correct me if I've misunderstood. I've got an app out in the wild which was processed by the Play Store by an earlier version of bundletool that I now can't easily update.

**Bundletool version(s) affected**
Version: 1.2.0

**Stacktrace**
```
[BT:1.2.0] Error: Both modules 'module1' and 'module2' contain asset entry 'assets/img123.webp'.
com.android.tools.build.bundletool.model.exceptions.InvalidBundleException: Both modules 'module1' and 'module2' contain asset entry 'assets/img123.webp'.
        at com.android.tools.build.bundletool.model.exceptions.UserExceptionBuilder.build(UserExceptionBuilder.java:58)
        at com.android.tools.build.bundletool.validation.EntryClashValidator.checkEntryClash(EntryClashValidator.java:85)
        at com.android.tools.build.bundletool.validation.EntryClashValidator.lambda$checkEntryClashes$0(EntryClashValidator.java:64)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
        at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
        at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:699)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
        at com.google.common.collect.CollectSpliterators$1WithCharacteristics.forEachRemaining(CollectSpliterators.java:65)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at com.android.tools.build.bundletool.validation.EntryClashValidator.checkEntryClashes(EntryClashValidator.java:60)
        at com.android.tools.build.bundletool.validation.EntryClashValidator.validateAllModules(EntryClashValidator.java:51)
        at com.android.tools.build.bundletool.validation.ValidatorRunner.validateBundleModulesUsingSubValidator(ValidatorRunner.java:75)
        at com.android.tools.build.bundletool.validation.ValidatorRunner.validateBundleUsingSubValidator(ValidatorRunner.java:69)
        at com.android.tools.build.bundletool.validation.ValidatorRunner.lambda$validateBundle$3(ValidatorRunner.java:58)
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:406)
        at com.android.tools.build.bundletool.validation.ValidatorRunner.validateBundle(ValidatorRunner.java:58)
        at com.android.tools.build.bundletool.validation.AppBundleValidator.validate(AppBundleValidator.java:104)
        at com.android.tools.build.bundletool.commands.BuildApksCommand.execute(BuildApksCommand.java:607)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:75)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:47)
```

**To Reproduce**
Create two bundles with a duplicate asset. Run build-apks

**Expected behavior**
Duplicate asset names are permitted if file contents are identical and asset only exists in asset modules.

**Comment by ymakhno** [comment]
Thank you for reporting this, will fix in the next release. Could you please share your usecase, why do you need the same file between different asset modules?

**Comment by simon-bond** [comment]
We have a large database of image assets for use in a battery of cognitive tests. Assets packs are downloaded for specific instances of a given task. Some images are reused between different types of tasks and consequently exist in different asset packs. Alternative strategies exist, but would be quite an upheaval for our asset generation mechanism (which is shared with a parallel implementation on iOS, where overlapping asset tags are permitted).

**Comment by ymakhno** [comment]
Fixed in 1.3.0.

**Comment by AbreuRodrigo** [comment]
Apparently this is back, I'm currently using version 1.6.0, and just got this:
`Bundletool failed: Failed to run 'C:/Program Files/Unity/Hub/Editor/2019.4.30f1/Editor/Data/PlaybackEngines/AndroidPlayer\OpenJDK\bin\java.exe -jar "D:\dev\gryphon_android\client\src\bundletool-all.jar" build-bundle --overwrite --config="C:\Users\rabreu\AppData\Local\Temp\BundleConfig.json" --modules=D:\dev\gryphon_android\client\build\play_asset_delivery\pre_build\bundles\bundles.zip,D:\dev\gryphon_android\client\build\play_asset_delivery\pre_build\audio_common\audio_common.zip,D:\dev\gryphon_android\client\build\play_asset_delivery\pre_build\audio_enUS\audio_enUS.zip,D:\dev\gryphon_android\client\build\play_asset_delivery\pre_build\audio_jaJP\audio_jaJP.zip,D:\dev\gryphon_android\client\build\play_asset_delivery\pre_build\audio_koKR\audio_koKR.zip,D:\dev\gryphon_android\client\build\play_asset_delivery\pre_build\audio_zhCN\audio_zhCN.zip,D:\dev\gryphon_android\client\build\play_asset_delivery\pre_build\audio_zhTW\audio_zhTW.zip,D:\dev\gryphon_android\client\build\play_asset_delivery\pre_build\base\base.zip --output="D:\dev\gryphon_android\client\build\local.Debug\Android\local.Debug.aab" --metadata-file=com.android.tools.build.libraries/dependencies.pb:D:\dev\gryphon_android\client\build\play_asset_delivery\pre_build\base\source\BUNDLE-METADATA\com.android.tools.build.libraries\dependencies.pb'
stdout:

stderr:
[BT:1.8.2] Error: Modules 'audio_common' and 'audio_enUS' contain entry 'assets/assetpack/Boss_Azurous.bnk' with different content.
com.android.tools.build.bundletool.model.exceptions.InvalidBundleException: Modules 'audio_common' and 'audio_enUS' contain entry 'assets/assetpack/Boss_Azurous.bnk' with different content.
	at com.android.tools.build.bundletool.model.exceptions.UserExceptionBuilder.build(UserExceptionBuilder.java:58)
	at com.android.tools.build.bundletool.validation.EntryClashValidator.checkEqualEntries(EntryClashValidator.java:98)
	at com.android.tools.build.bundletool.validation.EntryClashValidator.checkEntryClash(EntryClashValidator.java:87)
	at com.android.tools.build.bundletool.validation.EntryClashValidator.lambda$checkEntryClashes$0(EntryClashValidator.java:64)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at com.google.common.collect.CollectSpliterators$1WithCharacteristics.lambda$forEachRemaining$1(CollectSpliterators.java:67)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at com.google.common.collect.CollectSpliterators$1WithCharacteristics.forEachRemaining(CollectSpliterators.java:67)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.android.tools.build.bundletool.validation.EntryClashValidator.checkEntryClashes(EntryClashValidator.java:60)
	at com.android.tools.build.bundletool.validation.EntryClashValidator.validateAllModules(EntryClashValidator.java:51)
	at com.android.tools.build.bundletool.validation.ValidatorRunner.validateBundleModulesUsingSubValidator(ValidatorRunner.java:75)
	at com.android.tools.build.bundletool.validation.ValidatorRunner.lambda$validateBundleModules$4(ValidatorRunner.java:64)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:406)
	at com.android.tools.build.bundletool.validation.ValidatorRunner.validateBundleModules(ValidatorRunner.java:63)
	at com.android.tools.build.bundletool.validation.BundleModulesValidator.validate(BundleModulesValidator.java:82)
	at com.android.tools.build.bundletool.commands.BuildBundleCommand.execute(BuildBundleCommand.java:231)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:73)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:49)

exit code: 1

UnityEngine.Debug:LogError (object)
Google.Android.AppBundle.Editor.Internal.AppBundlePublisher:BuildForGryphon (UnityEditor.BuildPlayerOptions) (at Assets/External/GooglePlayPlugins/com.google.android.appbundle/Editor/Scripts/Internal/AppBundlePublisher.cs:253)
Gryphon.Pad.Editor.PadBuildHelper:BuildAndroidPlayer (UnityEditor.BuildPlayerOptions) (at Assets/PlayAssetDelivery/Scripts/Editor/PadBuildHelper.cs:36)
Gryphon.Editor.Build.GameBuilder/<>c__DisplayClass30_0:<BuildAndroidPlayer>b__0 () (at Assets/Editor/Build/Client/Game/GameBuilder.cs:712)
Gryphon.Editor.EditorUtils:ExecuteTimedFunc<UnityEditor.Build.Reporting.BuildReport> (System.Func`1<UnityEditor.Build.Reporting.BuildReport>) (at Assets/Editor/Utils/EditorUtils.cs:202)
Gryphon.Editor.Build.GameBuilder:BuildAndroidPlayer (Gryphon.Editor.Build.GameBuilder/GameBuildOptions,UnityEditor.BuildPlayerOptions) (at Assets/Editor/Build/Client/Game/GameBuilder.cs:710)
Gryphon.Editor.Build.GameBuilder:BuildPlayer (Gryphon.Editor.Build.GameBuilder/GameBuildOptions,Gryphon.Editor.Build.GameBuilderResults) (at Assets/Editor/Build/Client/Game/GameBuilder.cs:602)
Gryphon.Editor.Build.GameBuilder:Build (System.Nullable`1<UnityEditor.BuildTarget>,System.Action`1<bool>,Gryphon.Editor.Build.GameBuilder/GameBuildOptions) (at Assets/Editor/Build/Client/Game/GameBuilder.cs:474)
Gryphon.Editor.Build.GameBuilder:BuildAndroid (Gryphon.Editor.Build.GameBuilder/GameBuildOptions,System.Action`1<bool>) (at Assets/Editor/Build/Client/Game/GameBuilder.cs:137)
Gryphon.Editor.Build.GameBuilder:BuildGameWithCustomOptions (Gryphon.Editor.Build.GameBuilder/GameBuildOptions,System.Action`1<bool>) (at Assets/Editor/Build/Client/Game/GameBuilder.cs:212)
Gryphon.Editor.Build.BuildWindowGameTabContent:OnGUI_BuildButton () (at Assets/Editor/Build/Client/Game/BuildWindowGameTabContent.cs:588)
Gryphon.Editor.Build.BuildWindowGameTabContent:OnGUI_GryphonBuildContext () (at Assets/Editor/Build/Client/Game/BuildWindowGameTabContent.cs:137)
Gryphon.Editor.Build.BuildWindowGameTabContent:OnGUI_TabContent (Gryphon.Editor.Build.GameBuilder/GameBuildOptions) (at Assets/Editor/Build/Client/Game/BuildWindowGameTabContent.cs:77)
Gryphon.Editor.Build.GryphonBuildWindow:OnGUI () (at Assets/Editor/Build/Client/Game/GryphonBuildWindow.cs:118)
UnityEngine.GUIUtility:ProcessEvent (int,intptr)
`

**Comment by AbreuRodrigo** [comment]
Hey @ymakhno, I'm guessing this is back in version 1.6.0:
`Bundletool failed: Failed to run 'C:/Program Files/Unity/Hub/Editor/2019.4.30f1/Editor/Data/PlaybackEngines/AndroidPlayer\OpenJDK\bin\java.exe -jar "D:\dev\gryphon_android\client\src\bundletool-all.jar" build-bundle --overwrite --config="C:\Users\rabreu\AppData\Local\Temp\BundleConfig.json" --modules=D:\dev\gryphon_android\client\build\play_asset_delivery\pre_build\bundles\bundles.zip,D:\dev\gryphon_android\client\build\play_asset_delivery\pre_build\audio_common\audio_common.zip,D:\dev\gryphon_android\client\build\play_asset_delivery\pre_build\audio_enUS\audio_enUS.zip,D:\dev\gryphon_android\client\build\play_asset_delivery\pre_build\audio_jaJP\audio_jaJP.zip,D:\dev\gryphon_android\client\build\play_asset_delivery\pre_build\audio_koKR\audio_koKR.zip,D:\dev\gryphon_android\client\build\play_asset_delivery\pre_build\audio_zhCN\audio_zhCN.zip,D:\dev\gryphon_android\client\build\play_asset_delivery\pre_build\audio_zhTW\audio_zhTW.zip,D:\dev\gryphon_android\client\build\play_asset_delivery\pre_build\base\base.zip --output="D:\dev\gryphon_android\client\build\local.Debug\Android\local.Debug.aab" --metadata-file=com.android.tools.build.libraries/dependencies.pb:D:\dev\gryphon_android\client\build\play_asset_delivery\pre_build\base\source\BUNDLE-METADATA\com.android.tools.build.libraries\dependencies.pb'
stdout:

stderr:
[BT:1.8.2] Error: Modules 'audio_common' and 'audio_enUS' contain entry 'assets/assetpack/Boss_Azurous.bnk' with different content.
com.android.tools.build.bundletool.model.exceptions.InvalidBundleException: Modules 'audio_common' and 'audio_enUS' contain entry 'assets/assetpack/Boss_Azurous.bnk' with different content.
	at com.android.tools.build.bundletool.model.exceptions.UserExceptionBuilder.build(UserExceptionBuilder.java:58)
	at com.android.tools.build.bundletool.validation.EntryClashValidator.checkEqualEntries(EntryClashValidator.java:98)
	at com.android.tools.build.bundletool.validation.EntryClashValidator.checkEntryClash(EntryClashValidator.java:87)
	at com.android.tools.build.bundletool.validation.EntryClashValidator.lambda$checkEntryClashes$0(EntryClashValidator.java:64)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at com.google.common.collect.CollectSpliterators$1WithCharacteristics.lambda$forEachRemaining$1(CollectSpliterators.java:67)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at com.google.common.collect.CollectSpliterators$1WithCharacteristics.forEachRemaining(CollectSpliterators.java:67)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.android.tools.build.bundletool.validation.EntryClashValidator.checkEntryClashes(EntryClashValidator.java:60)
	at com.android.tools.build.bundletool.validation.EntryClashValidator.validateAllModules(EntryClashValidator.java:51)
	at com.android.tools.build.bundletool.validation.ValidatorRunner.validateBundleModulesUsingSubValidator(ValidatorRunner.java:75)
	at com.android.tools.build.bundletool.validation.ValidatorRunner.lambda$validateBundleModules$4(ValidatorRunner.java:64)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:406)
	at com.android.tools.build.bundletool.validation.ValidatorRunner.validateBundleModules(ValidatorRunner.java:63)
	at com.android.tools.build.bundletool.validation.BundleModulesValidator.validate(BundleModulesValidator.java:82)
	at com.android.tools.build.bundletool.commands.BuildBundleCommand.execute(BuildBundleCommand.java:231)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:73)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:49)

exit code: 1

UnityEngine.Debug:LogError (object)
Google.Android.AppBundle.Editor.Internal.AppBundlePublisher:BuildForGryphon (UnityEditor.BuildPlayerOptions) (at Assets/External/GooglePlayPlugins/com.google.android.appbundle/Editor/Scripts/Internal/AppBundlePublisher.cs:253)
Gryphon.Pad.Editor.PadBuildHelper:BuildAndroidPlayer (UnityEditor.BuildPlayerOptions) (at Assets/PlayAssetDelivery/Scripts/Editor/PadBuildHelper.cs:36)
Gryphon.Editor.Build.GameBuilder/<>c__DisplayClass30_0:<BuildAndroidPlayer>b__0 () (at Assets/Editor/Build/Client/Game/GameBuilder.cs:712)
Gryphon.Editor.EditorUtils:ExecuteTimedFunc<UnityEditor.Build.Reporting.BuildReport> (System.Func'1<UnityEditor.Build.Reporting.BuildReport>) (at Assets/Editor/Utils/EditorUtils.cs:202)
Gryphon.Editor.Build.GameBuilder:BuildAndroidPlayer (Gryphon.Editor.Build.GameBuilder/GameBuildOptions,UnityEditor.BuildPlayerOptions) (at Assets/Editor/Build/Client/Game/GameBuilder.cs:710)
Gryphon.Editor.Build.GameBuilder:BuildPlayer (Gryphon.Editor.Build.GameBuilder/GameBuildOptions,Gryphon.Editor.Build.GameBuilderResults) (at Assets/Editor/Build/Client/Game/GameBuilder.cs:602)
Gryphon.Editor.Build.GameBuilder:Build (System.Nullable'1<UnityEditor.BuildTarget>,System.Action'1<bool>,Gryphon.Editor.Build.GameBuilder/GameBuildOptions) (at Assets/Editor/Build/Client/Game/GameBuilder.cs:474)
Gryphon.Editor.Build.GameBuilder:BuildAndroid (Gryphon.Editor.Build.GameBuilder/GameBuildOptions,System.Action'1<bool>) (at Assets/Editor/Build/Client/Game/GameBuilder.cs:137)
Gryphon.Editor.Build.GameBuilder:BuildGameWithCustomOptions (Gryphon.Editor.Build.GameBuilder/GameBuildOptions,System.Action'1<bool>) (at Assets/Editor/Build/Client/Game/GameBuilder.cs:212)
Gryphon.Editor.Build.BuildWindowGameTabContent:OnGUI_BuildButton () (at Assets/Editor/Build/Client/Game/BuildWindowGameTabContent.cs:588)
Gryphon.Editor.Build.BuildWindowGameTabContent:OnGUI_GryphonBuildContext () (at Assets/Editor/Build/Client/Game/BuildWindowGameTabContent.cs:137)
Gryphon.Editor.Build.BuildWindowGameTabContent:OnGUI_TabContent (Gryphon.Editor.Build.GameBuilder/GameBuildOptions) (at Assets/Editor/Build/Client/Game/BuildWindowGameTabContent.cs:77)
Gryphon.Editor.Build.GryphonBuildWindow:OnGUI () (at Assets/Editor/Build/Client/Game/GryphonBuildWindow.cs:118)
UnityEngine.GUIUtility:ProcessEvent (int,intptr)`
