### ISSUE TITLE
Issue:   build-apks using bundletool-all-0.14.0.jar

### ISSUE THREAD

**Issue by kusumakara** [google/bundletool#184]
While building apks using bundletool i am getting below exeption on windows m/c.

**$ java -jar bundletool-all-0.14.0.jar build-apks --bundle=app.aab --output=apks.apks --mode=universal --ks=abc.keystore --ks-pass=pass:abc --ks-key-alias=abc**

**Exception:**

[BT:0.14.0] Error: com.android.tools.build.bundletool.model.Aapt2Command$Aapt2Exception: Command '[C:\Users\kodiak\AppData\Local\Temp\3772494146671548782\output\windows\aapt2.exe, convert, --output-format, binary, -o, C:\Users\kodiak\AppData\Local\Temp\9107970920454887369\binary.apk, C:\Users\kodiak
\AppData\Local\Temp\9107970920454887369\proto.apk]' didn't terminate successfully (exit code: -1073741701). Check the logs.
java.lang.RuntimeException: com.android.tools.build.bundletool.model.Aapt2Command$Aapt2Exception: Command '[C:\Users\kodiak\AppData\Local\Temp\3772494146671548782\output\windows\aapt2.exe, convert, --output-format, binary, -o, C:\Users\kodiak\AppData\Local\Temp\9107970920454887369\binary.apk, C:\Use
rs\kodiak\AppData\Local\Temp\9107970920454887369\proto.apk]' didn't terminate successfully (exit code: -1073741701). Check the logs.
        at com.android.tools.build.bundletool.io.ConcurrencyUtils.waitFor(ConcurrencyUtils.java:59)
        at com.android.tools.build.bundletool.io.ConcurrencyUtils.waitForAll(ConcurrencyUtils.java:42)
        at java.util.function.Function.lambda$andThen$1(Unknown Source)
        at java.util.stream.ReferencePipeline.collect(Unknown Source)
        at com.android.tools.build.bundletool.io.ApkSerializerManager.serializeApks(ApkSerializerManager.java:184)
        at com.android.tools.build.bundletool.io.ApkSerializerManager.populateApkSetBuilder(ApkSerializerManager.java:103)
        at com.android.tools.build.bundletool.commands.BuildApksManager.executeWithZip(BuildApksManager.java:251)
        at com.android.tools.build.bundletool.commands.BuildApksManager.execute(BuildApksManager.java:123)
        at com.android.tools.build.bundletool.commands.BuildApksCommand.execute(BuildApksCommand.java:523)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:75)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:47)

Please some one help me..

**Comment by ymakhno** [comment]
It is not enough information to understand the cause of the issue. aapt2 exception usually means a problem with application resources.

**Comment by plecesne** [comment]
Was there any log before that exception? Usually, aapt2 will print a log in the console before throwing.

**Comment by kusumakara** [comment]
@ymakhno ymakhno 

I am able to bundle successfully with below command.

### ./gradlew bundlearmeabiRelease 

To extract apks from app bundle used below command.

java -jar bundletool-all-0.14.0.jar build-apks --bundle=app.aab --output=apks.apks --mode=universal --ks=abc.keystore --ks-pass=pass:abc --ks-key-alias=abc

### One of the windows machine its working. Able to extract apk and installed successfully.

### If run same command on another windows machine its throughs  below exception.

`[BT:0.14.0] Error: com.android.tools.build.bundletool.model.Aapt2Command$Aapt2Exception: Command '[C:\Users\kodiak\AppData\Local\Temp\3772494146671548782\output\windows\aapt2.exe, convert, --output-format, binary, -o, C:\Users\kodiak\AppData\Local\Temp\9107970920454887369\binary.apk, C:\Users\kodiak
\AppData\Local\Temp\9107970920454887369\proto.apk]' didn't terminate successfully (exit code: -1073741701). Check the logs.
java.lang.RuntimeException: com.android.tools.build.bundletool.model.Aapt2Command$Aapt2Exception: Command '[C:\Users\kodiak\AppData\Local\Temp\3772494146671548782\output\windows\aapt2.exe, convert, --output-format, binary, -o, C:\Users\kodiak\AppData\Local\Temp\9107970920454887369\binary.apk, C:\Use
rs\kodiak\AppData\Local\Temp\9107970920454887369\proto.apk]' didn't terminate successfully (exit code: -1073741701). Check the logs.
        at com.android.tools.build.bundletool.io.ConcurrencyUtils.waitFor(ConcurrencyUtils.java:59)
        at com.android.tools.build.bundletool.io.ConcurrencyUtils.waitForAll(ConcurrencyUtils.java:42)
        at java.util.function.Function.lambda$andThen$1(Unknown Source)
        at java.util.stream.ReferencePipeline.collect(Unknown Source)
        at com.android.tools.build.bundletool.io.ApkSerializerManager.serializeApks(ApkSerializerManager.java:184)
        at com.android.tools.build.bundletool.io.ApkSerializerManager.populateApkSetBuilder(ApkSerializerManager.java:103)
        at com.android.tools.build.bundletool.commands.BuildApksManager.executeWithZip(BuildApksManager.java:251)
        at com.android.tools.build.bundletool.commands.BuildApksManager.execute(BuildApksManager.java:123)
        at com.android.tools.build.bundletool.commands.BuildApksCommand.execute(BuildApksCommand.java:523)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:75)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:47)
Caused by: java.util.concurrent.ExecutionException: com.android.tools.build.bundletool.model.Aapt2Command$Aapt2Exception: Command '[C:\Users\kodiak\AppData\Local\Temp\3772494146671548782\output\windows\aapt2.exe, convert, --output-format, binary, -o, C:\Users\kodiak\AppData\Local\Temp\91079709204548`

**Both machines configurations are same.**

**Comment by plecesne** [comment]
Was there any log before that exception? Usually, aapt2 will print a log in the console before throwing.

**Comment by kusumakara** [comment]
Command: C:\Users\kodiak\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\00ad1d0670003aacab555ab2c4e9c306\aapt2-3.2.1-4818971-windows\aapt2.exe link --proto-format\
          -I\
          F:\Gradle\android-sdk\platforms\android-29\android.jar\
          --manifest\
          F:\appBundle\Src\Product\HTMLPoCClient\Android_POC_Client\app\build\intermediates\merged_manifests\armeabiRelease\processArmeabiReleaseManifest\merged\AndroidManifest.xml\
          -o\
          F:\appBundle\Src\Product\HTMLPoCClient\Android_POC_Client\app\build\intermediates\linked_res_for_bundle\armeabiRelease\bundleArmeabiReleaseResources\bundled-res.ap_\
          --auto-add-overlay\
          -0\
          apk\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
