### ISSUE TITLE
Local testing unable to work on some devices

### ISSUE THREAD

**Issue by evowizz** [google/bundletool#196]
**Description:**
Local testing uses adb to create a folder on `/sdcard/Android/data/[package_name]/files/local_testing` and put splits in there for testing. Unfortunately, adb is not able to access `/sdcard/Android/data` on some devices.

This was observed on a Google Pixel 5, however, it worked correctly on a Google Pixel 4 XL.

**Bundletool Version:** 1.4.0

**Stacktrace:**
```
ADB << rm -rf '/sdcard/Android/data/[package_name]/files/local_testing'
ADB >> OK
ADB << mkdir -p '/sdcard/Android/data/[package_name]/files/local_testing' && rmdir '/sdcard/Android/data/[package_name]/files/local_testing' && mkdir -p '/sdcard/Android/data/[package_name]/files/local_testing'
ADB >> mkdir: '/sdcard/Android/data/[package_name]': Permission denied
[BT:1.4.0] Error: Pushing additional splits for local testing failed. Your app might still have been installed correctly, but you won't be able to test dynamic modules.
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Pushing additional splits for local testing failed. Your app might still have been installed correctly, but you won't be able to test dynamic modules.
        at com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57)
        at com.android.tools.build.bundletool.device.DdmlibDevice.pushApks(DdmlibDevice.java:205)
        at com.android.tools.build.bundletool.commands.InstallApksCommand.lambda$pushSplits$8(InstallApksCommand.java:267)
        at com.android.tools.build.bundletool.device.AdbRunner.run(AdbRunner.java:81)
        at com.android.tools.build.bundletool.device.AdbRunner.run(AdbRunner.java:43)
        at com.android.tools.build.bundletool.commands.InstallApksCommand.pushSplits(InstallApksCommand.java:267)
        at com.android.tools.build.bundletool.commands.InstallApksCommand.execute(InstallApksCommand.java:179)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:89)
        at com.android.tools.build.bundletool.device.DdmlibDevice$RemoteCommandExecutor.access$000(DdmlibDevice.java:220)
```

**To Reproduce:**
1. Connect your testing device
2. Run the following command:
`bundletool get-device-spec --output=device-spec.json && bundletool build-apks --device-spec=device-spec.json --bundle=app-release.aab --output=app-release.apks --local-testing && bundletool install-apks --apks=app-release.apks`

*Make sure to replace "app-release.aab" with the name of your own built .aab package.*

**Expected behavior:**
The command should run without any error and the splits should be pushed to the device correctly.

**Environment:**
Computer: Windows 10
ADB: `Android Debug Bridge version 1.0.41 / Version 30.0.5-6877874`
Testing device: Google Pixel 5 (redfin), Android 11 (RQ1A.201205.011)

**Additional context**
Scoped Storage caused a lot of damage and issues on Android. This could likely be the cause.

**Comment by ymakhno** [comment]
This issue is caused by bug in Android 11, there is no workaround available which we can apply in bundletool. 

Fortunately this bug is fixed already and all you need is to apply security updates on your device.
