### ISSUE TITLE
screenDensity supports only numbers, not 'xxxhdpi' values

### ISSUE THREAD

**Issue by YuriDenison** [google/bundletool#2]
**Describe the bug**
Documentation says it is possible to use 'xxxhdpi' values for 'screenDensity' key in device specification JSON. Currently it is impossible due to ''InvalidProtocolBufferException: Not an uint32 value: "xxxhdpi""

**Bundletool version(s) affected**
Version: [e.g. 0.3.3]

**Stacktrace**
```
com.android.tools.build.bundletool.exceptions.CommandExecutionException: I/O error while reading the device spec file 's9.json'.
	at com.android.tools.build.bundletool.exceptions.CommandExecutionException$Builder.build(CommandExecutionException.java:81)
	at com.android.tools.build.bundletool.commands.ExtractApksCommand.parseDeviceSpec(ExtractApksCommand.java:119)
	at com.android.tools.build.bundletool.commands.ExtractApksCommand.fromFlags(ExtractApksCommand.java:95)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:75)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:44)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Not an uint32 value: "xxxhdpi"
	at com.google.protobuf.util.JsonFormat$ParserImpl.parseUint32(JsonFormat.java:1590)
	at com.google.protobuf.util.JsonFormat$ParserImpl.parseFieldValue(JsonFormat.java:1761)
	at com.google.protobuf.util.JsonFormat$ParserImpl.mergeField(JsonFormat.java:1483)
	at com.google.protobuf.util.JsonFormat$ParserImpl.mergeMessage(JsonFormat.java:1315)
	at com.google.protobuf.util.JsonFormat$ParserImpl.merge(JsonFormat.java:1273)
	at com.google.protobuf.util.JsonFormat$ParserImpl.merge(JsonFormat.java:1135)
	at com.google.protobuf.util.JsonFormat$Parser.merge(JsonFormat.java:351)
	at com.android.tools.build.bundletool.commands.ExtractApksCommand.parseDeviceSpec(ExtractApksCommand.java:113)
```

**To Reproduce**
Steps to reproduce the behavior.
- add device configuration JSON from [documentation ](https://developer.android.com/guide/app-bundle/test)
```
{
  "supportedAbis": ["arm64-v8a", "armeabi-v7a"],
  "supportedLocales": ["en", "fr"],
  "screenDensity": xxxhdpi,
  "sdkVersion": 27
}

```
- run `java -jar bundletool-all-0.3.3.jar extract-apks --apks=app.apks --device-spec=device.json --output-dir=apks`

**Environment:**
OS: [Mac OS 10.13.4]

**Comment by plecesne** [comment]
Thank you for reporting this issue.
We have now updated our documentation.
