### ISSUE TITLE
ConcurrentModificationException when using DynamicInstallMonitor with Navigation Component

### ISSUE THREAD

**Issue by solamour** [google/bundletool#200]
**Describe the bug**
When using DynamicInstallMonitor with Navigation Component as described in https://developer.android.com/guide/navigation/navigation-dynamic#monitor, the app crashes with ConcurrentModificationException if the app is deployed by bundletool. The app works fine if deployed by "Internal app sharing" or "Internal testing".

**Bundletool version(s) affected**
Version: 1.4.0

**Stacktrace**
```
2021-01-10 10:18:10.237 7421-7421/org.solamour.myapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.solamour.myapp, PID: 7421
    java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
        at com.google.android.play.core.internal.af.c(Unknown Source:13)
        at com.google.android.play.core.splitinstall.testing.FakeSplitInstallManager.f(Unknown Source:7)
        at com.google.android.play.core.splitinstall.testing.g.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**To Reproduce**
Follow the example code in https://developer.android.com/guide/navigation/navigation-dynamic#monitor. 

**Expected behavior**
App shouldn't encounter ConcurrentModificationException.

**Known workaround**
When deploying the app for testing, use either "Internal app sharing" or "Internal testing".

**Environment:**
OS: Android 8.x

**Comment by plecesne** [comment]
From the stacktrace, it looks like a bug in Play Core. Could you please file a bug in [Play Core issue tracker](https://issuetracker.google.com/issues/new?component=384531) instead?
