### ISSUE TITLE
FATAL EXCEPTION: SplitCompatBackgroundThread

### ISSUE THREAD

**Issue by ekselys** [google/bundletool#202]
Hi all,

i'm facing this issue while trying to install an on demand module:

```
I/ProofFragment$installModule$1$listener: Install state: SplitInstallSessionState{sessionId=1, status=2, errorCode=0, bytesDownloaded=14142, totalBytesToDownload=21213, moduleNamesNullable=[dynamicfeature], languagesNullable=[], resolutionIntent=null, splitFileIntents=null}
I/ProofFragment$installModule$1$listener: Install state: SplitInstallSessionState{sessionId=1, status=2, errorCode=0, bytesDownloaded=21213, totalBytesToDownload=21213, moduleNamesNullable=[dynamicfeature], languagesNullable=[], resolutionIntent=null, splitFileIntents=null}
E/AndroidRuntime: FATAL EXCEPTION: SplitCompatBackgroundThread
    Process: com.ekselys.efesto, PID: 23511
    java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.android.play.core.splitinstall.f.a(java.util.List, com.google.android.play.core.splitinstall.d)' on a null object reference
        at com.google.android.play.core.splitinstall.testing.FakeSplitInstallManager.w(Unknown Source:21)
        at com.google.android.play.core.splitinstall.testing.FakeSplitInstallManager.d(Unknown Source:19)
        at com.google.android.play.core.splitinstall.testing.i.run(Unknown Source:10)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
V/FA: Recording user engagement, ms: 4145
```

I've installed the application through bundletool usage docs, the module is correctly present on the device (i can see the state of the fake download to proceed without problems).
The feature module contains just a fragment, this is the code used to install the feature module:

```kotlin
var id = 0;

val splitInstallManager = SplitInstallManagerFactory.create(requireActivity().applicationContext)

val listener = object : SplitInstallStateUpdatedListener {
    override fun onStateUpdate(state: SplitInstallSessionState) {
        logger.i("Install state: $state");
        if (state?.sessionId() == id) {
            if (state.hasTerminalStatus()) {
                splitInstallManager.unregisterListener(this)
            }
        }
    }
}

val request =
    SplitInstallRequest
        .newBuilder()
        .addModule("dynamicfeature")
        .build()

splitInstallManager.registerListener(listener)

splitInstallManager
    .startInstall(request)
    .addOnSuccessListener { sessionId -> logger.i("Download Installation completeed $sessionId") }
    .addOnFailureListener { exception -> logger.e(exception, "Download Installation completeed") }
```

Any ideas?

**Comment by ymakhno** [comment]
This looks like a bug in Play Core. Could you please file a bug their issue tracker instead? https://issuetracker.google.com/issues/new?component=384531
