### ISSUE TITLE
Not able to install apks file using latest bundletool on mac Big sur

### ISSUE THREAD

**Issue by NavalKishor** [google/bundletool#207]
**Describe the bug**
Not able to install apks file using latest bundletool

**Bundletool version(s) affected**
Version: [1.5.0] [0.12.0] [0.10.2]

**Stacktrace**
```
[BT:0.12.0] Error: Timed out while waiting for ADB.
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Timed out while waiting for ADB.
	at com.android.tools.build.bundletool.model.exceptions.CommandExecutionException$Builder.build(CommandExecutionException.java:81)
	at com.android.tools.build.bundletool.device.DeviceAnalyzer.getDeviceSpec(DeviceAnalyzer.java:88)
	at com.android.tools.build.bundletool.commands.InstallApksCommand.execute(InstallApksCommand.java:171)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:88)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:46)
Caused by: java.util.concurrent.TimeoutException: Timed out (60000 ms) while waiting for ADB.
	at com.android.tools.build.bundletool.device.AdbServer.waitTillInitialDeviceListPopulated(AdbServer.java:55)
	at com.android.tools.build.bundletool.device.AdbServer.getDevices(AdbServer.java:36)
	at com.android.tools.build.bundletool.device.DeviceAnalyzer.getTargetDevice(DeviceAnalyzer.java:140)
	at com.android.tools.build.bundletool.device.DeviceAnalyzer.getAndValidateDevice(DeviceAnalyzer.java:117)
	at com.android.tools.build.bundletool.device.DeviceAnalyzer.getDeviceSpec(DeviceAnalyzer.java:53)
	... 3 more
```
**To Reproduce**
Steps to reproduce the behavior.
prepare a bundle and then from bundle apks file and use this command
 >java -jar bundletool-all-0.10.2.jar install-apks --apks=app_bundle.apks

**Expected behavior**
apks extension file using above command should the install the app to device

**Known workaround**
i have found a workaround, same command is working on windows OS

**Environment:**
OS: MacBook Pro 11.2.1
android OS 11
 openjdk version "1.8.0_265"
OpenJDK Runtime Environment Corretto-8.265.01.1 (build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM Corretto-8.265.01.1 (build 25.265-b01, mixed mode)

$adb devices
List of devices attached
RX8Z2288NJA	device

**Comment by ymakhno** [comment]
I'm unable to reproduce on Big Sur, probably some environment issue.
