### ISSUE TITLE
Not able to convert opensource trichrome aab (89.0.4389.72) to apk

### ISSUE THREAD

**Issue by anppraveen** [google/bundletool#211]
**Describe the bug**
Not able to convert opensource trichrome aab (89.0.4389.72) to apk

**Bundletool version(s) affected**
Version: [e.g. 0.3.3]   1.5.0

**Stacktrace**
Copy all of the output of the command, including the stacktrace if visible.
(89.0.4389.6)$ java -jar "/home/ajit/Downloads/bundletool-all-1.4.0.jar" build-apks --bundle="/home/ajit/chromium/src/out/trichrome_32/apks/TrichromeChrome.aab" --output=simple.apks --mode=universal
INFO: The APKs will be signed with the debug keystore found at '/home/ajit/.android/debug.keystore'.
/tmp/7946686681591917154/proto.apk: error: failed to deserialize resources.pb: duplicate configuration in resource table.
/tmp/7946686681591917154/proto.apk: error: failed to load APK.
[BT:1.4.0] Error: Command '[/tmp/AutoValue_BuildApksCommand4701665354077569128/output/linux/aapt2, convert, --output-format, binary, -o, /tmp/7946686681591917154/binary.apk, /tmp/7946686681591917154/proto.apk]' didn't terminate successfully (exit code: 1). Check the logs.
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Command '[/tmp/AutoValue_BuildApksCommand4701665354077569128/output/linux/aapt2, convert, --output-format, binary, -o, /tmp/7946686681591917154/binary.apk, /tmp/7946686681591917154/proto.apk]' didn't terminate successfully (exit code: 1). Check the logs.
	at com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57)
	at com.android.tools.build.bundletool.model.DefaultCommandExecutor.executeImpl(DefaultCommandExecutor.java:57)
	at com.android.tools.build.bundletool.model.DefaultCommandExecutor.execute(DefaultCommandExecutor.java:33)
	at com.android.tools.build.bundletool.model.Aapt2Command$1.convertApkProtoToBinary(Aapt2Command.java:41)
	at com.android.tools.build.bundletool.io.ApkzlibApkSerializerHelper.writeToZipFile(ApkzlibApkSerializerHelper.java:122)
	at com.android.tools.build.bundletool.io.ApkzlibApkSerializerHelper.writeToZipFile(ApkzlibApkSerializerHelper.java:101)
	at com.android.tools.build.bundletool.io.StandaloneApkSerializer.writeToDiskInternal(StandaloneApkSerializer.java:76)
	at com.android.tools.build.bundletool.io.StandaloneApkSerializer.writeToDiskAsUniversal(StandaloneApkSerializer.java:47)
	at com.android.tools.build.bundletool.io.ApkSetBuilderFactory$ApkSetArchiveBuilder.addStandaloneUniversalApk(ApkSetBuilderFactory.java:138)
	at com.android.tools.build.bundletool.io.ApkSerializerManager$ApkSerializer.serialize(ApkSerializerManager.java:473)
	at com.android.tools.build.bundletool.io.ApkSerializerManager.lambda$null$3(ApkSerializerManager.java:225)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:117)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:38)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**To Reproduce**
Steps to reproduce the behavior.
Include the full command being run as well as, if possible, artifacts the bug can be reproduced with.
 java -jar "/home/ajit/Downloads/bundletool-all-1.4.0.jar" build-apks --bundle="/home/ajit/chromium/src/out/trichrome_32/apks/TrichromeChrome.aab" --output=simple.apks --mode=universal

**Expected behavior**
Apk should be generated.

**Known workaround**
If you have found a workaround, please specify what it is.
None
**Environment:**
OS: [e.g. iOS 10.3.3]
ubuntu 16.04

**Additional context**

**Comment by ymakhno** [comment]
This relates to outdated version of aapt2 which is included in bundletool. 
You may try to:
 * download newer version of aapt2 here: https://dl.google.com/android/maven2/com/android/tools/build/aapt2/7.0.0-alpha14-7147631/aapt2-7.0.0-alpha14-7147631-linux.jar;
 * unpack `aapt2` binary from downloaded jar;
 * use it in your command: `java -jar "/home/ajit/Downloads/bundletool-all-1.4.0.jar" build-apks --bundle="/home/ajit/chromium/src/out/trichrome_32/apks/TrichromeChrome.aab" --output=simple.apks --mode=universal --aapt2 <path to unpacked aapt2>`.

We will update aapt2 version included into bundletool in the next release.

**Comment by anppraveen** [comment]
> * [https://dl.google.com/android/maven2/com/android/tools/build/aapt2](https://dl.google.com/android/maven2/com/android/tools/build/aapt2/7.0.0-alpha14-7147631/aapt2-7.0.0-alpha14-7147631-linux.jar)

Hi,
Still not able to convert, Could you please try converting once.
Attached ab file for your reference.
[TrichromeChrome.zip](https://github.com/google/bundletool/files/6499039/TrichromeChrome.zip)


Thanks!!
