### ISSUE TITLE
Issue with ZipFlinger while running BundleTool locally

### ISSUE THREAD

**Issue by tanyaa-singh** [google/bundletool#218]
**Describe the bug**
I have recently imported BundleTool and doing some customisations in it. 
I have been trying to use BundleTool in my code, and added BundleTool in the dependency. However, when i try to run it locally, it fails with the following error: 

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/android/zipflinger/PayloadInputStream
	 at com.android.tools.build.bundletool.commands.BuildApksCommand.execute(BuildApksCommand.java:671)
         at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:75)
          at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:47)
Caused by: java.lang.ClassNotFoundException: com.android.zipflinger.PayloadInputStream
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
```
I can see that the issue is with the zipFlinger/paylodInputStream not found, but the zipflinger is included in the lib of my jar.
Not sure if I am doing anything wrong while importing the third-party-package in my package. Any leads would be really appreciated.

Thanks!
**Bundletool version(s) affected**
Version:1.5.0

**Expected behavior**
Expected to run the build-apks command locally.

**Environment:**
OS: macOS Mojave
Version: 10.14.6

**Additional context**

**Comment by ymakhno** [comment]
Are you using bundletool maven dependency?

If yes, could you please attach a sample project to reproduce the issue?
