### ISSUE TITLE
How to use bundletool for local ABI testing?

### ISSUE THREAD

**Issue by limin05030** [google/bundletool#225]
My steps:
step 1: create Native c++ project;
step 2: in app/build.gradle, add "android.bundle.abi.enableSplit=true"  and "implementation 'com.google.android.play:core-ktx:1.8.1'";
step 3: add "SplitCompat.install(this)" in application/attachBaseContext() and "SplitCompat.installActivity(this)" in MainActivity/attachBaseContext();
step 4: execute "gradlew bundleDebug", generate app-debug.aab;
step 5: execute "java -jar bundletool-all-1.7.0.jar build-apks --bundle=app-debug.aab --output=app-debug.apks --overwrite --local-testing", generate app-debug.apks;
step 6: execute "java -jar bundletool-all-1.7.0.jar install-apks --apks=app-debug.apks";

finally, launch this app, but it crashed:

2021-07-05 10:24:12.326 17468-17468/? E/linker: library "/system/lib64/libnative-lib.so" ("/system/lib64/libnative-lib.so") needed or dlopened by "/apex/com.android.art/lib64/libnativeloader.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="", permitted_paths="/data:/mnt/expand:/data/data/com.sens.appbundle2"]
2021-07-05 10:24:12.327 17468-17468/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sens.appbundle2, PID: 17468
    java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/lib64/libnative-lib.so" needed or dlopened by "/apex/com.android.art/lib64/libnativeloader.so" is not accessible for the namespace "classloader-namespace"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.sens.appbundle2.MainActivity.<clinit>(MainActivity.kt:37)
        ...

**Comment by ymakhno** [comment]
This issue doesn't relate to bundletool. Steps are correct but looks like you didn't build your native library.
