### ISSUE TITLE
Pushing additional splits for local testing failed. Your app might still have been installed correctly, but you won't be able to test dynamic modules

### ISSUE THREAD

**Issue by FortuneDream** [google/bundletool#243]
**Describe the bug**
I try to use bundletool to
The .aab file with "localtest" was installed on Android 11, but it failed

**Bundletool version(s) affected**
Bundle Version: [1.8.0]

**Stacktrace**
The APKs have been extracted in the directory: /var/folders/pj/j1lf72yd31121pbjs8xyt1sw0000gn/T/8737659789719145773
The APKs have been extracted in the directory: /var/folders/pj/j1lf72yd31121pbjs8xyt1sw0000gn/T/8737659789719145773
ADB << rm -rf '/sdcard/Android/data/com.kwai.video/files/local_testing'
ADB >> OK
ADB << mkdir -p '/sdcard/Android/data/com.kwai.video/files/local_testing' && rmdir '/sdcard/Android/data/com.kwai.video/files/local_testing' && mkdir -p '/sdcard/Android/data/com.kwai.video/files/local_testing'
ADB >> mkdir: '/sdcard/Android/data/com.kwai.video': Permission denied
[BT:1.8.0] Error: Pushing additional splits for local testing failed. Your app might still have been installed correctly, but you won't be able to test dynamic modules.
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Pushing additional splits for local testing failed. Your app might still have been installed correctly, but you won't be able to test dynamic modules.
        at com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57)
        at com.android.tools.build.bundletool.device.DdmlibDevice.push(DdmlibDevice.java:194)
        at com.android.tools.build.bundletool.commands.InstallApksCommand.lambda$pushFiles$9(InstallApksCommand.java:305)
        at com.android.tools.build.bundletool.device.AdbRunner.run(AdbRunner.java:81)
        at com.android.tools.build.bundletool.device.AdbRunner.run(AdbRunner.java:43)
        at com.android.tools.build.bundletool.commands.InstallApksCommand.pushFiles(InstallApksCommand.java:305)
        at com.android.tools.build.bundletool.commands.InstallApksCommand.execute(InstallApksCommand.java:216)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:91)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:49)
Caused by: java.io.IOException: ADB command failed.
        at com.android.tools.build.bundletool.device.DdmlibDevice$RemoteCommandExecutor.executeAndPrint(DdmlibDevice.java:296)
        at com.android.tools.build.bundletool.device.DdmlibDevice$RemoteCommandExecutor.access$000(DdmlibDevice.java:254)
        at com.android.tools.build.bundletool.device.DdmlibDevice.push(DdmlibDevice.java:180)
        ... 7 more

**To Reproduce**
./bundletool build-apks --bundle=$OUTPUT_FILE --output=$APP_OUTPUT --overwrite --local-testing 
./bundletool install-apks --apks=$APP_OUTPUT

**Environment:**
Android 11
MIUI 12.5.9.0
Mi 11
Android security update :2021.6.1

**Additional context**

**Comment by fadeltd** [comment]
I'm also experiencing this in my emulator, specific to Android 11 (API 30)

```sh
[BT:1.8.0] Error: Pushing additional splits for local testing failed. Your app might still have been installed correctly, but you won't be able to test dynamic modules.
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Pushing additional splits for local testing failed. Your app might still have been installed correctly, but you won't be able to test dynamic modules.
	at com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57)
	at com.android.tools.build.bundletool.device.DdmlibDevice.push(DdmlibDevice.java:194)
	at com.android.tools.build.bundletool.commands.InstallApksCommand.lambda$pushFiles$9(InstallApksCommand.java:305)
	at com.android.tools.build.bundletool.device.AdbRunner.run(AdbRunner.java:81)
	at com.android.tools.build.bundletool.device.AdbRunner.run(AdbRunner.java:43)
	at com.android.tools.build.bundletool.commands.InstallApksCommand.pushFiles(InstallApksCommand.java:305)
	at com.android.tools.build.bundletool.commands.InstallApksCommand.execute(InstallApksCommand.java:216)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:91)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:49)
Caused by: java.io.IOException: ADB command failed.
	at com.android.tools.build.bundletool.device.DdmlibDevice$RemoteCommandExecutor.executeAndPrint(DdmlibDevice.java:296)
	at com.android.tools.build.bundletool.device.DdmlibDevice$RemoteCommandExecutor.access$000(DdmlibDevice.java:254)
	at com.android.tools.build.bundletool.device.DdmlibDevice.push(DdmlibDevice.java:180)
	... 7 more
```

**Comment by ymakhno** [comment]
This is duplicate of #196.

Unfortunately nothing we can do about this exception on bundletool side because this is Android storage issue. As a workaround you may use [Internal app sharing](https://play.google.com/console/about/internalappsharing) or another device.

**Comment by Chrn0924** [comment]
你们只会关闭issues吗？难道你们的KPI是靠关闭issues来的？
