### ISSUE TITLE
output flag error

### ISSUE THREAD

**Issue by IgorGanapolsky** [google/bundletool#25]
Hello, I am following instructions here - https://developer.android.com/guide/app-bundle/test.  It says to run the following command
`bundletool build-apks --bundle=/MyApp/my_app.aab --output=/MyApp/my_app.apks`

So I do **java -jar bundletool-all-0.5.0.jar build-apks --bundle=~/workspace/git/google/android-dynamic-features --output=my.apk**

However, bundletool errors out with the following
> Error: Flag --output should be the path where to generate the APK Set. Its extension must be '.apks'.
com.android.tools.build.bundletool.exceptions.ValidationException: Flag --output should be the path where to generate the APK Set. Its extension must be '.apks'.
	at com.android.tools.build.bundletool.exceptions.ValidationException$Builder.build(ValidationException.java:49)
	at com.android.tools.build.bundletool.exceptions.ValidationException$Builder.build(ValidationException.java:41)
	at com.android.tools.build.bundletool.commands.BuildApksCommand$Builder.build(BuildApksCommand.java:265)
	at com.android.tools.build.bundletool.commands.BuildApksCommand.fromFlags(BuildApksCommand.java:353)
	at com.android.tools.build.bundletool.commands.BuildApksCommand.fromFlags(BuildApksCommand.java:273)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:73)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:44)

**Comment by plecesne** [comment]
I think the error message is quite explicit as to what the problem is in your command. What is the behaviour you'd expect?

**Comment by IgorGanapolsky** [comment]
@plecesne I expect output **my.apk**

**Comment by plecesne** [comment]
I would recommend you read the documentation again: the "build-apks" command builds an "APK Set" (with the ".apks" extension). To extract the APKs for a given device, you can then run the "extract-apks" command. Alternatively you can run the "install-apks" command to install them directly on a connected device.

Change the extension of the output to ".apks" as suggested by the error message.

**Comment by IgorGanapolsky** [comment]
@plecesne It doesn't explain what **aab** is for --bundle
