### ISSUE TITLE
Error: The app doesn't support ABI architectures of the device.

### ISSUE THREAD

**Issue by SabianF** [google/bundletool#257]
**Describe the bug**
After exporting the APKS from the AAP, trying to install them to my emulated device using
```bash
java -jar "$BUNDLE_TOOL_PATH" install-apks --apks="$APKS_FILE"
```
fails with
```
[BT:1.8.2] Error: The app doesn't support ABI architectures of the device. Device ABIs: [x86], app ABIs: [armeabi-v7a, arm64-v8a, x86_64].
com.android.tools.build.bundletool.model.exceptions.IncompatibleDeviceException: The app doesn't support ABI architectures of the device. Device ABIs: [x86], app ABIs: [armeabi-v7a, arm64-v8a, x86_64].
```

**Bundletool version(s) affected**
Version: 1.8.2

**Stacktrace**
```
[BT:1.8.2] Error: The app doesn't support ABI architectures of the device. Device ABIs: [x86], app ABIs: [armeabi-v7a, arm64-v8a, x86_64].
com.android.tools.build.bundletool.model.exceptions.IncompatibleDeviceException: The app doesn't support ABI architectures of the device. Device ABIs: [x86], app ABIs: [armeabi-v7a, arm64-v8a, x86_64].
        at com.android.tools.build.bundletool.model.exceptions.UserExceptionBuilder.build(UserExceptionBuilder.java:58)
        at com.android.tools.build.bundletool.device.AbiMatcher.checkDeviceCompatibleInternal(AbiMatcher.java:115)
        at com.android.tools.build.bundletool.device.AbiMatcher.checkDeviceCompatibleInternal(AbiMatcher.java:36)
        at com.android.tools.build.bundletool.device.TargetingDimensionMatcher.checkDeviceCompatible(TargetingDimensionMatcher.java:119)
        at com.android.tools.build.bundletool.device.VariantMatcher.checkCompatibleWithVariantTargetingHelper(VariantMatcher.java:123)
        at com.android.tools.build.bundletool.device.VariantMatcher.lambda$checkCompatibleWithVariantTargeting$3(VariantMatcher.java:107)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
        at com.android.tools.build.bundletool.device.VariantMatcher.checkCompatibleWithVariantTargeting(VariantMatcher.java:107)
        at com.android.tools.build.bundletool.device.VariantMatcher.checkCompatibleWithVariant(VariantMatcher.java:102)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at com.android.tools.build.bundletool.device.VariantMatcher.getAllMatchingVariants(VariantMatcher.java:84)
        at com.android.tools.build.bundletool.device.VariantMatcher.getMatchingVariant(VariantMatcher.java:98)
        at com.android.tools.build.bundletool.device.ApkMatcher.getMatchingApks(ApkMatcher.java:135)
        at com.android.tools.build.bundletool.commands.ExtractApksCommand.execute(ExtractApksCommand.java:199)
        at com.android.tools.build.bundletool.commands.ExtractApksCommand.execute(ExtractApksCommand.java:181)
        at com.android.tools.build.bundletool.commands.InstallApksCommand.getApksToInstall(InstallApksCommand.java:264)
        at com.android.tools.build.bundletool.commands.InstallApksCommand.execute(InstallApksCommand.java:195)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:91)
```

**To Reproduce**
My `.sh` file is
```sh
echo "Setting variables needed for arguments (These will be different for each person)..."
BUNDLE_TOOL_PATH=[REDACTED]
BUNDLE_AAP_FILE=[REDACTED]
APKS_FILE=[REDACTED]
KEYSTORE_FILE=[REDACTED]
KEYSTORE_PASS=file:[REDACTED]
KEYSTORE_KEY_ALIAS=[REDACTED]
KEYSTORE_KEY_PASS=file:[REDACTED]
echo "Setting variables Done"
echo
echo "Showing variables for confirmation..."
echo "BUNDLE_TOOL_PATH=$BUNDLE_TOOL_PATH"
echo "BUNDLE_AAP_FILE=$BUNDLE_AAP_FILE"
echo "APKS_FILE=$APKS_FILE"
echo "KEYSTORE_FILE=$KEYSTORE_FILE"
echo "KEYSTORE_PASS=$KEYSTORE_PASS"
echo "KEYSTORE_KEY_ALIAS=$KEYSTORE_KEY_ALIAS"
echo "KEYSTORE_KEY_PASS=$KEYSTORE_KEY_PASS"
echo
if test -f "$BUNDLE_AAP_FILE"; then
    echo "Deleting old app bundle (AAP) file..."
    rm "$BUNDLE_AAP_FILE"
    echo "Deleting old app bundle (AAP) file done"
    echo
fi
echo "Building new app bundle (AAP) file with keys defined in AndroidManifest..."
flutter build appbundle
echo "Building AAP Done"
echo
if test -f "$APKS_FILE"; then
    echo "Deleting old APKS file..."
    rm "$APKS_FILE"
    echo "Deleting old APKS file done"
    echo
fi
echo "Exporting the .apks to simulate installing from Google Play..."
java -jar "$BUNDLE_TOOL_PATH" build-apks --bundle="$BUNDLE_AAP_FILE" --output="$APKS_FILE" --ks="$KEYSTORE_FILE" --ks-pass="$KEYSTORE_PASS" --ks-key-alias="$KEYSTORE_KEY_ALIAS" --key-pass="$KEYSTORE_KEY_PASS"
echo "Exporting APKS Done"
echo
echo "Installing the apks to the emulated device as a production app..."
java -jar "$BUNDLE_TOOL_PATH" install-apks --apks="$APKS_FILE"
echo "Installing APKS Done"
echo
echo "Clearing variables after execution finished..."
unset BUNDLE_TOOL_PATH
unset BUNDLE_AAP_FILE
unset APKS_FILE
unset KEYSTORE_FILE
unset KEYSTORE_PASS
unset KEYSTORE_KEY_ALIAS
unset KEYSTORE_KEY_PASS
echo "Clearing variables Done"
echo
echo "All Done!"
```

**Expected behavior**
I expected the APKS to be installed on my running emulated device

**Known workaround**
N/A

**Environment:**
OS: Windows 10 Home 10.0.18363 (x64 bit)
Android emulator: Pixel 3a API 29 using Android 10.0 x86
Android SDK: Android 11.0 (R) API 30 revision 3
`/src/android/app/build.gradle` (for `flutter build appbundle`)
```
android.signingConfigs.release {    
    // Ensuring gradle uses our signing key when building for release
    keyAlias keystoreProperties['keyAlias']
    keyPassword keystoreProperties['keyPassword']
    storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
    storePassword keystoreProperties['storePassword']
}
```

**Additional context**
Everything executes fine except `install-apks`

I'm following exactly the instructions on [Flutter's](https://docs.flutter.dev/deployment/android#test-the-app-bundle) and [Android's](https://developer.android.com/studio/command-line/bundletool#deploy_with_bundletool) docs, so I'm not sure why I'm encountering so many problems. This is just the last one in a long line of undocumented, very hard to search problems I've encountered.

I did notice the device ABI is x86, so I'm looking into that right now, but I have little experience with this.

**Comment by SabianF** [comment]
I'm at Android Studio's create new AVD flow, and all the system images are x86, and since I didn't notice any ABI parameters for `bundletool`, I'm at a loss

![image](https://user-images.githubusercontent.com/58588133/143515440-739e85ec-e4ea-404c-88c7-2e929c440c0a.png)

**Comment by SabianF** [comment]
Oh, jeez...

![image](https://user-images.githubusercontent.com/58588133/143515533-6772e106-4606-470c-b5ef-28e55489b369.png)

**Comment by SabianF** [comment]
When I try to run the arm64 AVD, the android emulator launcher window is hanging at 5 bars, and a new process is created in Windows with minimal CPU usage, before eventually terminating.
```
%USERPROFILE%\AppData\Local\Android\Sdk\emulator\emulator64-crash-service.exe  -pipe \\.\pipe\AndroidEmulatorCrashService.16688 -ppid 16688 -data-dir %USERPROFILE%\AppData\Local\Temp\\AndroidEmulator\52a1a5be-4e5f-11ec-9d12-38d547996536 
```

**Comment by ymakhno** [comment]
Bundletool informs you that you are trying to run your app which supports the following ABIs: `[armeabi-v7a, arm64-v8a, x86_64]` on `x86` emulator.

There is no bundletool issue here. You can either add `x86` ABI support to your app or use `x86_64` emulator.
