### ISSUE TITLE
failed build-apks  from aab with flavors

### ISSUE THREAD

**Issue by lincleejun** [google/bundletool#26]
**Describe the bug**
I was download [aab](https://github.com/googlesamples/android-dynamic-features) example from google samples， and add a flavordimension in it. flavor detail as below
`
android {
    flavorDimensions "mode", "app"

    productFlavors {

        bugcheck {
            dimension "mode"

            defaultConfig {
                targetSdkVersion 21

                ndk {
                    abiFilter "armeabi-v7a"
                }

                // for lambda support.
                compileOptions {
                    sourceCompatibility JavaVersion.VERSION_1_8
                    targetCompatibility JavaVersion.VERSION_1_8
                }
            }
        }

        dogfood {
            dimension "mode"

            defaultConfig {
                targetSdkVersion 21

                ndk {
                    abiFilter "armeabi-v7a"
                }

                // for lambda support.
                compileOptions {
                    sourceCompatibility JavaVersion.VERSION_1_8
                    targetCompatibility JavaVersion.VERSION_1_8
                }
            }
        }

        pro {
            minSdkVersion 14

            dimension "app"
        }

        normal {
            minSdkVersion 14

            dimension "app"
        }
    }
}`

use `./gradlew clean app:bundleDogfoodProDebug` to build bundle, 
got a app.aab,

finally use ` bundletool build-apks --bundle=./app/build/outputs/bundle/bugcheckProDebug/app.aab --output=outputs.apks` to extract apks 
face a crash

`
Error: Program type already present: com.google.android.samples.dynamicfeatures.ondemand.BuildConfig
[BT:0.5.1] Error: Dex merging failed.
com.android.tools.build.bundletool.exceptions.CommandExecutionException: Dex merging failed.
        at com.android.tools.build.bundletool.mergers.D8DexMerger.translateD8Exception(D8DexMerger.java:98)
        at com.android.tools.build.bundletool.mergers.D8DexMerger.merge(D8DexMerger.java:77)
        at com.android.tools.build.bundletool.mergers.ModuleSplitsToShardMerger.mergeDexFiles(ModuleSplitsToShardMerger.java:225)
        at com.android.tools.build.bundletool.mergers.ModuleSplitsToShardMerger.lambda$mergeDexFilesAndCache$0(ModuleSplitsToShardMerger.java:192)
        at java.util.HashMap.computeIfAbsent(HashMap.java:1118)
        at com.android.tools.build.bundletool.mergers.ModuleSplitsToShardMerger.mergeDexFilesAndCache(ModuleSplitsToShardMerger.java:190)
        at com.android.tools.build.bundletool.mergers.ModuleSplitsToShardMerger.mergeSingleShard(ModuleSplitsToShardMerger.java:138)
        at com.android.tools.build.bundletool.mergers.ModuleSplitsToShardMerger.merge(ModuleSplitsToShardMerger.java:92)
        at com.android.tools.build.bundletool.splitters.BundleSharder.shardBundle(BundleSharder.java:103)
        at com.android.tools.build.bundletool.commands.BuildApksManager.generateStandaloneApks(BuildApksManager.java:300)
        at com.android.tools.build.bundletool.commands.BuildApksManager.execute(BuildApksManager.java:165)
        at com.android.tools.build.bundletool.io.TempFiles.withTempDirectoryReturning(TempFiles.java:52)
        at com.android.tools.build.bundletool.commands.BuildApksCommand.execute(BuildApksCommand.java:368)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:73)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:44)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
        at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:76)
        at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:45)
        at com.android.tools.r8.D8.run(D8.java:67)
        at com.android.tools.build.bundletool.mergers.D8DexMerger.merge(D8DexMerger.java:70)
        ... 13 more
Caused by: com.android.tools.r8.utils.AbortException
        at com.android.tools.r8.utils.Reporter.failIfPendingErrors(Reporter.java:77)
        at com.android.tools.r8.utils.Reporter.fatalError(Reporter.java:58)
        at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:67)
        ... 16 more
`

**Bundletool version(s) affected**
Version: BundleTool 0.5.1

**Expected behavior**
normal get apks

**Environment:**
OS: [e.g. iOS 10.3.3]

**Comment by ymakhno** [comment]
I'm unable to reproduce this with the latest AGP and bundletool, please reopen if it is still relevant.
