### ISSUE TITLE
Target of the get-size command not found

### ISSUE THREAD

**Issue by joes0451** [google/bundletool#266]
UPDATE:

Sorry, it looks like I just left out adding "total" in the command.

I just did:

C:\Dev\Bundle_Util>SET PATH="C:/OpenJdk/openjdk-1.8.0.265-3.b01";%PATH%&&java -j
ar C:/bundletool-master/bundletool-all-1.8.2.jar get-size total --apks="C:/Andro
id/Dev/HurricaneTrackerG/Output.apks"
MIN,MAX
2245012,2245012

The .apks file exists in:  "C:/Android/Dev/HurricaneTrackerG/Output.apks"

And I issued this command:

SET PATH="C:/OpenJdk/openjdk-1.8.0.265-3.b01";%PATH%&&java -jar C:/bundletool-master/bundletool-all-1.8.2.jar get-size --apks="C:/Android/Dev/HurricaneTrackerG/Output.apks" --human-readable-sizes

Resulting in this error message:

C:\Dev\Bundle_Util>SET PATH="C:/OpenJdk/openjdk-1.8.0.265-3.b01";%PATH%&&java -jar C:/bundletool-master/bundletool-all-1.8.2.jar get-size --apks=C:/Android/Dev/HurricaneTrackerG/Output.apks --human-readable-sizes
[BT:1.8.2] Error: Target of the get-size command not found.
com.android.tools.build.bundletool.model.exceptions.InvalidCommandException: Target of the get-size command not found.
	at c om.android.tools.build.bundletool.model.exceptions. InvalidCommandException$$Lambda$6/13012286.create( Unknown Source)
	at c om.android.tools.build.bundletool.model.exceptions. InternalExceptionBuilder.build( InternalExceptionBuilder.java:57)
	at c om.android.tools.build.bundletool.commands. GetSizeCommand.lambda$parseGetSizeSubCommand$0(GetSizeCommand. java:224)
	at com.android.tools.build.bundletool.commands.GetSizeCommand$$Lambda$5/5629103.get(Unknown Source)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at c om.android.tools.build.bundletool.commands. GetSizeCommand.parseGetSizeSubCommand(GetSizeCommand.java:220)
	at com.android.tools.build.bundletool.commands.GetSizeCommand.fromFlags(GetSizeCommand.java:200)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:106)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:49)

So why am I getting this error?
Do I need another option set?

Thanks

**Comment by ymakhno** [comment]
You missed `total` word in the later command.
