### ISSUE TITLE
Unable to deploy apks to device

### ISSUE THREAD

**Issue by phileo99** [google/bundletool#270]
**Describe the bug**
Following this instruction from:
https://developer.android.com/studio/command-line/bundletool#deploy_with_bundletool

And after confirming connected device with `adb devices`, This command to install fails:
`bundletool install-apks --apks=/MyApp/my_app.apks`

with this crash stacktrace:
```
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Unable to find the requested device.
	at com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57)
	at com.android.tools.build.bundletool.device.DeviceAnalyzer.lambda$getAndValidateDevice$1(DeviceAnalyzer.java:128)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.android.tools.build.bundletool.device.DeviceAnalyzer.getAndValidateDevice(DeviceAnalyzer.java:124)
	at com.android.tools.build.bundletool.device.DeviceAnalyzer.getDeviceSpec(DeviceAnalyzer.java:53)
	at com.android.tools.build.bundletool.commands.InstallApksCommand.execute(InstallApksCommand.java:185)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:91)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:49)
```

**Bundletool version(s) affected**
Version: 1.8.2

**Stacktrace**
```
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Unable to find the requested device.
	at com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57)
	at com.android.tools.build.bundletool.device.DeviceAnalyzer.lambda$getAndValidateDevice$1(DeviceAnalyzer.java:128)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.android.tools.build.bundletool.device.DeviceAnalyzer.getAndValidateDevice(DeviceAnalyzer.java:124)
	at com.android.tools.build.bundletool.device.DeviceAnalyzer.getDeviceSpec(DeviceAnalyzer.java:53)
	at com.android.tools.build.bundletool.commands.InstallApksCommand.execute(InstallApksCommand.java:185)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:91)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:49)
```

**To Reproduce**
```
bundletool install-apks --apks=/MyApp/my_app.apks
```
**Expected behavior**
That bundletool will install apks into connected device according to documentation

**Additional context**

**Comment by phileo99** [comment]
ok, I have discovered that this combination works:
`bundletool install-apks  --device-id=RF8N30B2LWP --apks=/MyApp/my_app.apks`

Can the documentation please be updated as pre-requisite for closing this issue ?

**Comment by ymakhno** [comment]
`--device-id` flag is required when multiple devices are connected. For single connected device `device-id` is optional.
