### ISSUE TITLE
NPE while attempting to install APKS

### ISSUE THREAD

**Issue by Kamilake** [google/bundletool#275]
**Describe the bug**
Installing from apks to a connected device cause NPE

**Bundletool version(s) affected**
Version: 1.9.0

**Stacktrace**
```log
PS H:\Android> java -jar bundletool.jar install-apks --apks=aa.apks --allow-downgrade
[BT:1.9.0] Error: null
java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:878)
        at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:220)
        at com.google.common.io.ByteSource.read(ByteSource.java:286)
        at com.android.tools.build.bundletool.model.utils.ResultUtils.readTableOfContentFromApksArchive(ResultUtils.java:59)
        at com.android.tools.build.bundletool.model.utils.ResultUtils.readTableOfContents(ResultUtils.java:47)
        at com.android.tools.build.bundletool.commands.InstallApksCommand.readBuildApksResult(InstallApksCommand.java:354)
        at com.android.tools.build.bundletool.commands.InstallApksCommand.execute(InstallApksCommand.java:178)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:91)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:49)
```

**To Reproduce**
Steps to reproduce the behavior.
Include the full command being run as well as, if possible, artifacts the bug can be reproduced with.

Issue the following command to install `apks` to the connected device:
 
 ```bash
 java -jar bundletool.jar install-apks --apks=aa.apks --allow-downgrade
 ```

**Expected behavior**

**Known workaround**
If you have found a workaround, please specify what it is.

**Environment:**
OS: Windows 10 20H2, Z Fold2 + Pixel 2 android 10(AVD), Java 8 9 11 17

**Additional context**

I tried [this(#49)](https://github.com/google/bundletool/issues/49), but the result was the same.

**Comment by ymakhno** [comment]
This looks like corrupted APKS file. Is this APKS created by `bundletool build-apks`?

**Comment by ymakhno** [comment]
Inactive issue.
