### ISSUE TITLE
Windows cannot install multi apks zip

### ISSUE THREAD

**Issue by pandas2hy** [google/bundletool#277]
**Describe the bug**
bundletool will use the `：` as the apk separator, and the windows disk `D:\Users`, the `D` and `\Users` are recognized as apk, which makes it impossible to install

**Bundletool version(s) affected**
Version: [1.9.0]

**Stacktrace**
```
java -jar D:\bundletool-all-1.9.0.jar install-multi-apks --apks-zip=G:\mainline\S\mainline.zip
PS D:\Users\Desktop> java -jar D:\bundletool-all-1.9.0.jar install-multi-apks --apks-zip=G:\mainline\S\mainline.zip
The APKs have been extracted in the directory: D:\Users\AppData\Local\Temp\2174985961210144770
The APKs have been extracted in the directory: D:\Users\AppData\Local\Temp\2594069434522389964
The APKs have been extracted in the directory: D:\Users\AppData\Local\Temp\6009211119367560314
The APKs have been extracted in the directory: D:\Users\AppData\Local\Temp\4475181283139284856
The APKs have been extracted in the directory: D:\Users\AppData\Local\Temp\3412228818528667401
The APKs have been extracted in the directory: D:\Users\AppData\Local\Temp\3516467310282376784
The APKs have been extracted in the directory: D:\Users\AppData\Local\Temp\260837782393009429
The APKs have been extracted in the directory: D:\Users\AppData\Local\Temp\2694054867362910730
The APKs have been extracted in the directory: D:\Users\AppData\Local\Temp\4996992591120710421
The APKs have been extracted in the directory: D:\Users\AppData\Local\Temp\2067905867172689247
The APKs have been extracted in the directory: D:\Users\AppData\Local\Temp\1720547563818625467
The APKs have been extracted in the directory: D:\Users\AppData\Local\Temp\4488888132491917439
The APKs have been extracted in the directory: D:\Users\AppData\Local\Temp\413113928528525281
The APKs have been extracted in the directory: D:\Users\AppData\Local\Temp\3371948720426111174
The APKs have been extracted in the directory: D:\Users\AppData\Local\Temp\5086549301329632637
The APKs have been extracted in the directory: D:\Users\AppData\Local\Temp\8972613409499086853
The APKs have been extracted in the directory: D:\Users\AppData\Local\Temp\5231614302391635199
The APKs have been extracted in the directory: D:\Users\AppData\Local\Temp\6445614530172721622
The APKs have been extracted in the directory: D:\Users\AppData\Local\Temp\6981194515114464733
The APKs have been extracted in the directory: D:\Users\AppData\Local\Temp\4370422151155419705
The APKs have been extracted in the directory: D:\Users\AppData\Local\Temp\9026613215047373303
The APKs have been extracted in the directory: D:\Users\AppData\Local\Temp\8897304663917381820
The APKs have been extracted in the directory: D:\Users\AppData\Local\Temp\2409679767786808479
The APKs have been extracted in the directory: D:\Users\AppData\Local\Temp\516825785832576808
四月 02, 2022 11:57:58 上午 com.android.tools.build.bundletool.commands.InstallMultiApksCommand shouldInstall
警告: A higher version of package 'com.google.mainline.telemetry' (311402004 vs 311501004) is already present on device, skipping.
The APKs have been extracted in the directory: D:\Users\ \AppData\Local\Temp\5498155528656860750
The APKs have been extracted in the directory: D:\Users\ \AppData\Local\Temp\8120912581287518723
The APKs have been extracted in the directory: D:\Users\ \AppData\Local\Temp\288575094151460416
四月 02, 2022 11:57:58 上午 com.android.tools.build.bundletool.commands.InstallMultiApksCommand extractApkListFromApks
信息: Extracting package 'com.google.android.os.statsd'
The APKs have been extracted in the directory: D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.os.statsd
四月 02, 2022 11:57:58 上午 com.android.tools.build.bundletool.commands.InstallMultiApksCommand extractApkListFromApks
信息: Extracting package 'com.google.android.media'
The APKs have been extracted in the directory: D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.media
四月 02, 2022 11:57:58 上午 com.android.tools.build.bundletool.commands.InstallMultiApksCommand extractApkListFromApks
信息: Extracting package 'com.google.android.conscrypt'
The APKs have been extracted in the directory: D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.conscrypt
四月 02, 2022 11:57:58 上午 com.android.tools.build.bundletool.commands.InstallMultiApksCommand extractApkListFromApks
信息: Extracting package 'com.google.android.sdkext'
The APKs have been extracted in the directory: D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.sdkext
四月 02, 2022 11:57:58 上午 com.android.tools.build.bundletool.commands.InstallMultiApksCommand extractApkListFromApks
信息: Extracting package 'com.google.android.modulemetadata'
The APKs have been extracted in the directory: D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.modulemetadata
四月 02, 2022 11:57:58 上午 com.android.tools.build.bundletool.commands.InstallMultiApksCommand extractApkListFromApks
信息: Extracting package 'com.google.android.wifi'
The APKs have been extracted in the directory: D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.wifi
四月 02, 2022 11:57:58 上午 com.android.tools.build.bundletool.commands.InstallMultiApksCommand extractApkListFromApks
信息: Extracting package 'com.google.android.tzdata3'
The APKs have been extracted in the directory: D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.tzdata3
四月 02, 2022 11:57:58 上午 com.android.tools.build.bundletool.commands.InstallMultiApksCommand extractApkListFromApks
信息: Extracting package 'com.google.android.media.swcodec'
The APKs have been extracted in the directory: D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.media.swcodec
四月 02, 2022 11:57:58 上午 com.android.tools.build.bundletool.commands.InstallMultiApksCommand extractApkListFromApks
信息: Extracting package 'com.google.android.art'
The APKs have been extracted in the directory: D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.art
四月 02, 2022 11:57:58 上午 com.android.tools.build.bundletool.commands.InstallMultiApksCommand extractApkListFromApks
信息: Extracting package 'com.google.android.cellbroadcast'
The APKs have been extracted in the directory: D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.cellbroadcast
四月 02, 2022 11:57:58 上午 com.android.tools.build.bundletool.commands.InstallMultiApksCommand extractApkListFromApks
信息: Extracting package 'com.google.android.permission'
The APKs have been extracted in the directory: D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.permission
四月 02, 2022 11:57:58 上午 com.android.tools.build.bundletool.commands.InstallMultiApksCommand extractApkListFromApks
信息: Extracting package 'com.google.android.tethering'
The APKs have been extracted in the directory: D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.tethering
四月 02, 2022 11:57:58 上午 com.android.tools.build.bundletool.commands.InstallMultiApksCommand extractApkListFromApks
信息: Extracting package 'com.google.android.neuralnetworks'
The APKs have been extracted in the directory: D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.neuralnetworks
四月 02, 2022 11:57:58 上午 com.android.tools.build.bundletool.commands.InstallMultiApksCommand extractApkListFromApks
信息: Extracting package 'com.google.android.captiveportallogin'
The APKs have been extracted in the directory: D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.captiveportallogin
四月 02, 2022 11:57:58 上午 com.android.tools.build.bundletool.commands.InstallMultiApksCommand extractApkListFromApks
信息: Extracting package 'com.google.android.permissioncontroller'
The APKs have been extracted in the directory: D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.permissioncontroller
四月 02, 2022 11:57:58 上午 com.android.tools.build.bundletool.commands.InstallMultiApksCommand extractApkListFromApks
信息: Extracting package 'com.google.android.extservices'
The APKs have been extracted in the directory: D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.extservices
四月 02, 2022 11:57:58 上午 com.android.tools.build.bundletool.commands.InstallMultiApksCommand extractApkListFromApks
信息: Extracting package 'com.google.android.ext.services'
The APKs have been extracted in the directory: D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.ext.services
四月 02, 2022 11:57:58 上午 com.android.tools.build.bundletool.commands.InstallMultiApksCommand extractApkListFromApks
信息: Extracting package 'com.google.android.adbd'
The APKs have been extracted in the directory: D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.adbd
四月 02, 2022 11:57:59 上午 com.android.tools.build.bundletool.commands.InstallMultiApksCommand extractApkListFromApks
信息: Extracting package 'com.google.android.documentsui'
The APKs have been extracted in the directory: D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.documentsui
四月 02, 2022 11:57:59 上午 com.android.tools.build.bundletool.commands.InstallMultiApksCommand extractApkListFromApks
信息: Extracting package 'com.google.android.ipsec'
The APKs have been extracted in the directory: D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.ipsec
四月 02, 2022 11:57:59 上午 com.android.tools.build.bundletool.commands.InstallMultiApksCommand extractApkListFromApks
信息: Extracting package 'com.google.android.resolv'
The APKs have been extracted in the directory: D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.resolv
四月 02, 2022 11:57:59 上午 com.android.tools.build.bundletool.commands.InstallMultiApksCommand extractApkListFromApks
信息: Extracting package 'com.google.mainline.primary.libs'
The APKs have been extracted in the directory: D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.mainline.primary.libs
四月 02, 2022 11:57:59 上午 com.android.tools.build.bundletool.commands.InstallMultiApksCommand extractApkListFromApks
信息: Extracting package 'com.google.android.networkstack.permissionconfig'
The APKs have been extracted in the directory: D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.networkstack.permissionconfig
四月 02, 2022 11:57:59 上午 com.android.tools.build.bundletool.commands.InstallMultiApksCommand extractApkListFromApks
信息: Extracting package 'com.google.android.networkstack'
The APKs have been extracted in the directory: D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.networkstack
四月 02, 2022 11:57:59 上午 com.android.tools.build.bundletool.commands.InstallMultiApksCommand extractApkListFromApks
信息: Extracting package 'com.google.android.scheduling'
The APKs have been extracted in the directory: D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.scheduling
四月 02, 2022 11:57:59 上午 com.android.tools.build.bundletool.commands.InstallMultiApksCommand extractApkListFromApks
信息: Extracting package 'com.google.android.mediaprovider'
The APKs have been extracted in the directory: D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.mediaprovider
四月 02, 2022 11:57:59 上午 com.android.tools.build.bundletool.androidtools.AdbCommand$DefaultAdbCommand installMultiPackage
信息: Executing: G:\platform-tools\adb.exe install-multi-package D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.os.statsd\standalone-armeabi_v7a.arm64_v8a.apex D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.media\standalone-armeabi_v7a.arm64_v8a.apex D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.conscrypt\standalone-armeabi_v7a.arm64_v8a.apex D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.sdkext\standalone-arm64_v8a.apex D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.modulemetadata\base-master.apk D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.wifi\standalone-arm64_v8a.apex D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.tzdata3\standalone-arm64_v8a.apex D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.media.swcodec\standalone-arm64_v8a.apex D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.art\standalone-armeabi_v7a.arm64_v8a.apex D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.cellbroadcast\standalone-arm64_v8a.apex D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.permission\standalone-arm64_v8a.apex D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.tethering\standalone-armeabi_v7a.arm64_v8a.apex D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.neuralnetworks\standalone-armeabi_v7a.arm64_v8a.apex D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.captiveportallogin\base-xhdpi.apk:D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.captiveportallogin\base-master.apk D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.permissioncontroller\base-xhdpi.apk:D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.permissioncontroller\base-master.apk D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.extservices\standalone-arm64_v8a.apex D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.ext.services\base-xhdpi.apk:D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.ext.services\base-master.apk:D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.ext.services\base-arm64_v8a.apk D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.adbd\standalone-armeabi_v7a.arm64_v8a.apex D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.documentsui\base-xhdpi.apk:D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.documentsui\base-master.apk D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.ipsec\standalone-arm64_v8a.apex D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.resolv\standalone-arm64_v8a.apex D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.mainline.primary.libs\standalone-armeabi_v7a.arm64_v8a.apex D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.networkstack.permissionconfig\base-xhdpi.apk:D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.networkstack.permissionconfig\base-master.apk D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.networkstack\base-xhdpi.apk:D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.networkstack\base-master.apk:D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.networkstack\base-arm64_v8a.apk D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.scheduling\standalone-arm64_v8a.apex D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.mediaprovider\standalone-arm64_v8a.apex
adb: failed to stat D: No such file or directory
Attempting to abandon session ID 1239158753
Attempting to abandon session ID 940601814
Created parent session ID 940601814.
Created child session ID 1239158753.
Success
[BT:1.9.0] Error: Command '[G:\platform-tools\adb.exe, install-multi-package, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.os.statsd\standalone-armeabi_v7a.arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.media\standalone-armeabi_v7a.arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.conscrypt\standalone-armeabi_v7a.arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.sdkext\standalone-arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.modulemetadata\base-master.apk, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.wifi\standalone-arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.tzdata3\standalone-arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.media.swcodec\standalone-arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.art\standalone-armeabi_v7a.arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.cellbroadcast\standalone-arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.permission\standalone-arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.tethering\standalone-armeabi_v7a.arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.neuralnetworks\standalone-armeabi_v7a.arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.captiveportallogin\base-xhdpi.apk:D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.captiveportallogin\base-master.apk, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.permissioncontroller\base-xhdpi.apk:D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.permissioncontroller\base-master.apk, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.extservices\standalone-arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.ext.services\base-xhdpi.apk:D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.ext.services\base-master.apk:D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.ext.services\base-arm64_v8a.apk, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.adbd\standalone-armeabi_v7a.arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.documentsui\base-xhdpi.apk:D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.documentsui\base-master.apk, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.ipsec\standalone-arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.resolv\standalone-arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.mainline.primary.libs\standalone-armeabi_v7a.arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.networkstack.permissionconfig\base-xhdpi.apk:D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.networkstack.permissionconfig\base-master.apk, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.networkstack\base-xhdpi.apk:D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.networkstack\base-master.apk:D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.networkstack\base-arm64_v8a.apk, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.scheduling\standalone-arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.mediaprovider\standalone-arm64_v8a.apex]' didn't terminate successfully (exit code: 1). Check the logs.
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Command '[G:\platform-tools\adb.exe, install-multi-package, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.os.statsd\standalone-armeabi_v7a.arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.media\standalone-armeabi_v7a.arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.conscrypt\standalone-armeabi_v7a.arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.sdkext\standalone-arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.modulemetadata\base-master.apk, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.wifi\standalone-arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.tzdata3\standalone-arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.media.swcodec\standalone-arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.art\standalone-armeabi_v7a.arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.cellbroadcast\standalone-arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.permission\standalone-arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.tethering\standalone-armeabi_v7a.arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.neuralnetworks\standalone-armeabi_v7a.arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.captiveportallogin\base-xhdpi.apk:D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.captiveportallogin\base-master.apk, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.permissioncontroller\base-xhdpi.apk:D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.permissioncontroller\base-master.apk, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.extservices\standalone-arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.ext.services\base-xhdpi.apk:D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.ext.services\base-master.apk:D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.ext.services\base-arm64_v8a.apk, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.adbd\standalone-armeabi_v7a.arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.documentsui\base-xhdpi.apk:D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.documentsui\base-master.apk, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.ipsec\standalone-arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.resolv\standalone-arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.mainline.primary.libs\standalone-armeabi_v7a.arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.networkstack.permissionconfig\base-xhdpi.apk:D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.networkstack.permissionconfig\base-master.apk, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.networkstack\base-xhdpi.apk:D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.networkstack\base-master.apk:D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.networkstack\base-arm64_v8a.apk, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.scheduling\standalone-arm64_v8a.apex, D:\Users\ \AppData\Local\Temp\8347427246593913414\com.google.android.mediaprovider\standalone-arm64_v8a.apex]' didn't terminate successfully (exit code: 1). Check the logs.
        at com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57)
        at com.android.tools.build.bundletool.androidtools.DefaultCommandExecutor.executeImpl(DefaultCommandExecutor.java:57)
        at com.android.tools.build.bundletool.androidtools.DefaultCommandExecutor.executeAndCapture(DefaultCommandExecutor.java:39)
        at com.android.tools.build.bundletool.androidtools.AdbCommand$DefaultAdbCommand.installMultiPackage(AdbCommand.java:100)
        at com.android.tools.build.bundletool.androidtools.AdbCommand$DefaultAdbCommand.installMultiPackage(AdbCommand.java:59)
        at com.android.tools.build.bundletool.commands.InstallMultiApksCommand.execute(InstallMultiApksCommand.java:277)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:96)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:49)
```

**To Reproduce**
input this command in windows
```
java -jar D:\bundletool-all-1.9.0.jar install-multi-apks --apks-zip=G:\mainline\S\mainline.zip
```
The structure of this file mainline.zip is as follows：
└── vendor
    └── partner_modules
        ├── AdbdPrebuilt
        │   ├── Android.bp
        │   ├── LICENSE
        │   └── com.google.android.adbd_trimmed.apks
        ├── ArtPrebuilt
        │   ├── Android.bp
        │   ├── LICENSE
        │   └── com.google.android.art.apks
        ├── CaptivePortalLoginPrebuilt
        │   ├── Android.bp
        │   ├── CaptivePortalLoginGoogle.apks
        │   └── LICENSE
        ├── CellBroadcastPrebuilt
        │   ├── Android.bp
        │   ├── GoogleCellBroadcast_config.xml
        │   ├── GoogleCellBroadcast_permissions.xml
        │   ├── LICENSE
        │   └── com.google.android.cellbroadcast.apks
        ├── ConscryptPrebuilt
        │   ├── Android.bp
        │   ├── LICENSE
        │   └── com.google.android.conscrypt.apks

**Expected behavior**
All apks can installed successful

**Known workaround**
I cannot use it to install multi-apks on Windows

**Environment:**
Windows 10

**Additional context**

**Comment by ymakhno** [comment]
Should be fixed in the latest version.
