### ISSUE TITLE
command: no GL extensions found.

### ISSUE THREAD

**Issue by JulianKingman** [google/bundletool#278]
**Describe the bug**
On an m1 Mac, trying to install apks on an emulator, I get the error `Error: Unexpected output of 'dumpsys SurfaceFlinger' command: no GL extensions found.`
A google search turns up nothing...

**Bundletool version(s) affected**
Version: 2.2.22

**Stacktrace**
```bash
bundletool install-apks --apks /Users/julian/Downloads/myapp.apks --device-id emulator-5554
[BT:1.9.1] Error: Unexpected output of 'dumpsys SurfaceFlinger' command: no GL extensions found.
com.android.tools.build.bundletool.model.exceptions.AdbOutputParseException: Unexpected output of 'dumpsys SurfaceFlinger' command: no GL extensions found.
	at com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57)
	at com.android.tools.build.bundletool.device.GlExtensionsParser.parse(GlExtensionsParser.java:72)
	at com.android.tools.build.bundletool.device.DdmlibDevice.getGlExtensions(DdmlibDevice.java:147)
	at com.android.tools.build.bundletool.device.DeviceAnalyzer.getDeviceSpec(DeviceAnalyzer.java:62)
	at com.android.tools.build.bundletool.commands.InstallApksCommand.execute(InstallApksCommand.java:185)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:91)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:49)
```

**To Reproduce**
1. Convert aab to APKs
1. Attempt to install APKs onto emulator

**Expected behavior**
Successfully installs APK

**Known workaround**
None

**Environment:**
OS: macOS 12.3

**Additional context**

**Comment by dmitrievaGelena** [comment]
@ymakhno 
Hi, 
I have reproduced
Apple M1 Ventura 13.1

I'm entering:   bundletool install-apks --apks=/Users/nodl-e/Desktop/release.apks
Gives me back:  Error: Unexpected output of 'dumpsys SurfaceFlinger' command: no GL extensions found.
com.android.tools.build.bundletool.model.exceptions.AdbOutputParseException: Unexpected output of 'dumpsys SurfaceFlinger' command: no GL extensions found.
Device: Redmi Note 8 Pro 12.0.8
I changed the device to Samsung and everything worked, there may be problems with the devices of the Redmi line

**Comment by ymakhno** [comment]
Hi Gelena,

Could you please invoke `adb shell dumpsys SurfaceFlinger` on the affected device and attach its output?

**Comment by dmitrievaGelena** [comment]
@ymakhno 
Hi, I entered: adb shell dumpsys SurfaceFlinger

console gave me: nothing
Did the command need to be entered in the console or in android studio?

**Comment by MrGuoRanDuo** [comment]
I'm reproduce  in OPPO R9m@Android5.1 .
`java -jar /AEApps/AutoTest/dist/bundletool-all-1.15.5.jar install-apks --apks=/AEApps/AutoTest/test/pe_1_0_0_mys_en_android_gl_googleplay_20231018175639.apks --device-id=Y54L6LDQ9T4D6HMZ --timeout-millis=1200000 `
`WARNING: Unexpected output of 'dumpsys SurfaceFlinger' command: no GL extensions found.
[BT:1.15.5] Error: SDK version (22) of the device is not supported.
com.android.tools.build.bundletool.model.exceptions.IncompatibleDeviceException: SDK version (22) of the device is not supported.
at com.android.tools.build.bundletool.model.exceptions.UserExceptionBuilder.build(UserExceptionBuilder.java:58)
at com.android.tools.build.bundletool.device.SdkVersionMatcher.checkDeviceCompatibleInternal(SdkVersionMatcher.java:132)
at com.android.tools.build.bundletool.device.SdkVersionMatcher.checkDeviceCompatibleInternal(SdkVersionMatcher.java:31)
at com.android.tools.build.bundletool.device.TargetingDimensionMatcher.checkDeviceCompatible(TargetingDimensionMatcher.java:121)
at com.android.tools.build.bundletool.device.VariantMatcher.checkCompatibleWithVariantTargetingHelper(VariantMatcher.java:157)
at com.android.tools.build.bundletool.device.VariantMatcher.lambda$checkCompatibleWithVariantTargeting$4(VariantMatcher.java:141)
...too much stacks`
Run adb manually:`adb -s Y54L6LDQ9T4D6HMZ  shell dumpsys SurfaceFlinger`  too much stacks but normally print:
first line:`Build configuration: [sf] [libui] [libgui] 
Sync configuration: [using: EGL_ANDROID_native_fence_sync EGL_KHR_wait_sync]
DispSync configuration: app phase -8000000 ns, sf phase -8000000 ns, present offset 0 ns (refresh 16798253 ns)
Visible layers (count = 13)
...
...
Total allocated (estimate): 110349.50 KB`

**Comment by MrGuoRanDuo** [comment]
I'm reproduce  in OPPO R9m@Android5.1 .
`java -jar /xxxx/dist/bundletool-all-1.15.5.jar install-apks --apks=/AEApps/AutoTest/test/xxxxx.apks --device-id=Y54L6LDQ9T4D6HMZ --timeout-millis=1200000 `
`WARNING: Unexpected output of 'dumpsys SurfaceFlinger' command: no GL extensions found.
[BT:1.15.5] Error: SDK version (22) of the device is not supported.
com.android.tools.build.bundletool.model.exceptions.IncompatibleDeviceException: SDK version (22) of the device is not supported.
at com.android.tools.build.bundletool.model.exceptions.UserExceptionBuilder.build(UserExceptionBuilder.java:58)
at com.android.tools.build.bundletool.device.SdkVersionMatcher.checkDeviceCompatibleInternal(SdkVersionMatcher.java:132)
at com.android.tools.build.bundletool.device.SdkVersionMatcher.checkDeviceCompatibleInternal(SdkVersionMatcher.java:31)
at com.android.tools.build.bundletool.device.TargetingDimensionMatcher.checkDeviceCompatible(TargetingDimensionMatcher.java:121)
at com.android.tools.build.bundletool.device.VariantMatcher.checkCompatibleWithVariantTargetingHelper(VariantMatcher.java:157)
at com.android.tools.build.bundletool.device.VariantMatcher.lambda$checkCompatibleWithVariantTargeting$4(VariantMatcher.java:141)
...too much stacks`
Run adb manually:`adb -s Y54L6LDQ9T4D6HMZ  shell dumpsys SurfaceFlinger`  too much stacks but normally print:
first line:`Build configuration: [sf] [libui] [libgui] 
Sync configuration: [using: EGL_ANDROID_native_fence_sync EGL_KHR_wait_sync]
DispSync configuration: app phase -8000000 ns, sf phase -8000000 ns, present offset 0 ns (refresh 16798253 ns)
Visible layers (count = 13)
...
...
Total allocated (estimate): 110349.50 KB`
