### ISSUE TITLE
bundletool first install apks fail,but the second overwrite installation is normal

### ISSUE THREAD

**Issue by wei-spring** [google/bundletool#296]
**Describe the bug**
When i build an aab using android studio，android generate a apks,then use bundletool first install apks fail,but the second overwrite installation is normal

**Bundletool version(s) affected**
Version: [e.g. 1.9.1  1.11.0]

**Stacktrace**
`2022-07-11 15:04:05.430 30882-30930/? E/lment.loan.cas: Loaded layer handle (13413910317327575057) for layer /my_product/lib64/libcolorx-loader.so
2022-07-11 15:04:05.430 30882-30930/? E/lment.loan.cas: Looking for entrypoint ColorX_Check
2022-07-11 15:04:05.430 30882-30930/? E/lment.loan.cas: Found ColorX_Check for /my_product/lib64/libcolorx-loader.so
2022-07-11 15:04:05.430 30882-30930/? E/lment.loan.cas: Check failed
2022-07-11 15:04:05.448 30882-30882/? E/lment.loan.cas: sysOpen failed with error=Permission denied
2022-07-11 15:04:05.459 30882-30882/? E/SoLoader: couldn't find DSO to load: libjscexecutor.so
    	SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/com.loanmoto.installment.loan.cash/lib-main flags = 1]
    	SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/~~l5whGRlPPMHAft8szmpzaw==/com.loanmoto.installment.loan.cash-i82yB_NXb9tQwtunwZjjCw==/lib/arm64 flags = 0]
    	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
    	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
    	Native lib dir: /data/app/~~l5whGRlPPMHAft8szmpzaw==/com.loanmoto.installment.loan.cash-i82yB_NXb9tQwtunwZjjCw==/lib/arm64
     result: 0
2022-07-11 15:04:05.461 30882-30934/? E/SoLoader: couldn't find DSO to load: libhermes.so
    	SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/com.loanmoto.installment.loan.cash/lib-main flags = 1]
    	SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/~~l5whGRlPPMHAft8szmpzaw==/com.loanmoto.installment.loan.cash-i82yB_NXb9tQwtunwZjjCw==/lib/arm64 flags = 0]
    	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
    	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
    	Native lib dir: /data/app/~~l5whGRlPPMHAft8szmpzaw==/com.loanmoto.installment.loan.cash-i82yB_NXb9tQwtunwZjjCw==/lib/arm64
     result: 0
    
    --------- beginning of crash
2022-07-11 15:04:05.462 30882-30934/? E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.loanmoto.installment.loan.cash, PID: 30882
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
    	SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/com.loanmoto.installment.loan.cash/lib-main flags = 1]
    	SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/~~l5whGRlPPMHAft8szmpzaw==/com.loanmoto.installment.loan.cash-i82yB_NXb9tQwtunwZjjCw==/lib/arm64 flags = 0]
    	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
    	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
    	Native lib dir: /data/app/~~l5whGRlPPMHAft8szmpzaw==/com.loanmoto.installment.loan.cash-i82yB_NXb9tQwtunwZjjCw==/lib/arm64
     result: 0
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:896)
        at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:725)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:649)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:629)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:577)
        at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
        at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:27)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:952)
        at java.lang.Thread.run(Thread.java:920)
2022-07-11 15:04:05.467 30882-30934/? E/info: couldn't find DSO to load: libhermes.so
    	SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/com.loanmoto.installment.loan.cash/lib-main flags = 1]
    	SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/~~l5whGRlPPMHAft8szmpzaw==/com.loanmoto.installment.loan.cash-i82yB_NXb9tQwtunwZjjCw==/lib/arm64 flags = 0]
    	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
    	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
    	Native lib dir: /data/app/~~l5whGRlPPMHAft8szmpzaw==/com.loanmoto.installment.loan.cash-i82yB_NXb9tQwtunwZjjCw==/lib/arm64
     result: 0`

**To Reproduce**
1、create an React Native Project ("react-native": "0.61.4",);
2、build-apks
3、install-apks

Result:
launcher fail

4、install-apks
Result：
launcher normal

**Environment:**
OS: [e.g. Android 12]

**Comment by ymakhno** [comment]
Does not looks like bundletool issue, as it reports that you do not have `libhermes.so` library.
