### ISSUE TITLE
Error while loading private key and certificates from the keystore

### ISSUE THREAD

**Issue by jeffrylgh** [google/bundletool#300]
I execute "java -jar bundletool-xxx.jar build-apks --bundle=weka-obfuscated.aab --output=weka.apks --ks=../../KeyInfo/weka_key.jks --ks-key-alias=weka_key", there is a problem after entering the password

**Comment by Sstrip** [comment]
Me too. Have you solved it?

**Comment by khungnguyen** [comment]
Having same problem
[BT:1.14.1] Error: Error while loading private key and certificates from the keystore.
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Error while loading private key and certificates from the keystore.
        at com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57)
        at com.android.tools.build.bundletool.model.SignerConfig.extractFromKeystore(SignerConfig.java:180)
        at com.android.tools.build.bundletool.commands.BuildApksCommand.populateSigningConfigurationFromFlags(BuildApksCommand.java:1688)
        at com.android.tools.build.bundletool.commands.BuildApksCommand.fromFlags(BuildApksCommand.java:786)
        at com.android.tools.build.bundletool.commands.BuildApksCommand.fromFlags(BuildApksCommand.java:752)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:83)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:55)
Caused by: java.io.IOException: Invalid keystore format
        at sun.security.provider.JavaKeyStore.engineLoad(Unknown Source)
        at sun.security.provider.JavaKeyStore$JKS.engineLoad(Unknown Source)
        at sun.security.provider.KeyStoreDelegator.engineLoad(Unknown Source)
        at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(Unknown Source)
        at java.security.KeyStore.load(Unknown Source)
        at com.android.tools.build.bundletool.model.SignerConfig.extractFromKeystore(SignerConfig.java:133)
        ... 5 more
I can  be sure that I provided right keystore information : Alias + passwork. Don't know what's happening now
Could anyone help us?
Thank you

**Comment by wq1110** [comment]
me too

**Comment by Allison001** [comment]
me too,who solved it?

**Comment by TJHello** [comment]
me too,who solved it?

**Comment by fflin** [comment]
just user jdk17 to fix it

**Comment by chanbenny111** [comment]
use different jdk version work for me。bundletool-all-1.15.0 use java 11
