### ISSUE TITLE
Error: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl1259681499.tmp/base.apk (at Binary XML file line #0): <service> does not have valid android:name

### ISSUE THREAD

**Issue by Alekhya03** [google/bundletool#302]
C:\Users\alekhya.uppala>java -jar C:\Users\alekhya.uppala\Downloads\bundletool-all-1.11.2.jar install-apks --apks=C:\Users\alekhya.uppala\luavmandroid_aab_96_protected.apks
The APKs have been extracted in the directory: C:\Users\ALEKHY~1.UPP\AppData\Local\Temp\4013536960753711653
02:51:11 E/SplitApkInstallerBase: Failed to commit install session 1259681499 with command cmd package install-commit 1259681499. Error: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl1259681499.tmp/base.apk (at Binary XML file line #0): <service> does not have valid android:name
[BT:1.11.2] Error: Installation of the app failed.
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Installation of the app failed.
        at com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57)
        at com.android.tools.build.bundletool.device.DdmlibDevice.installApks(DdmlibDevice.java:205)
        at com.android.tools.build.bundletool.commands.InstallApksCommand.lambda$execute$2(InstallApksCommand.java:214)
        at com.android.tools.build.bundletool.device.AdbRunner.run(AdbRunner.java:81)
        at com.android.tools.build.bundletool.device.AdbRunner.run(AdbRunner.java:43)
        at com.android.tools.build.bundletool.commands.InstallApksCommand.execute(InstallApksCommand.java:214)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:105)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:54)
Caused by: com.android.ddmlib.InstallException: Failed to commit install session 1259681499 with command cmd package install-commit 1259681499. Error: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl1259681499.tmp/base.apk (at Binary XML file line #0): <service> does not have valid android:name
        at com.android.ddmlib.SplitApkInstallerBase.installCommit(SplitApkInstallerBase.java:99)
        at com.android.ddmlib.SplitApkInstaller.install(SplitApkInstaller.java:85)
        at com.android.ddmlib.internal.DeviceImpl.installPackages(DeviceImpl.java:1166)
        at com.android.tools.build.bundletool.device.DdmlibDevice.installApks(DdmlibDevice.java:189)
        ... 6 more

**Comment by Alekhya03** [comment]
Trying to install using the bundletool .Could you please help us resolve the issue

**Comment by ymakhno** [comment]
Issue is with your the application and errors shows where it is: `<service> does not have valid android:name`. Does not relate to bundletool,

**Comment by Alekhya03** [comment]
We are facing this issue only while using when we are generating the apk from aab file. In other case its working
