### ISSUE TITLE
Breaking change in release v1.12

### ISSUE THREAD

**Issue by nZeus** [google/bundletool#303]
**Describe the bug**
The new version of the `BundleTool` that was released today includes a breaking change and should have been released with a major number change.
It requires a new version of Java Runtime.
We get the following error now:
`BundleToolMain has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`
```
C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\8.0.345-1\x64\bin\java.exe -jar D:\a\1\s\bundletool-all-1.12.0.jar build-apks --bundle=D:\a\1\s\Buddy.App\Buddy.App.Android\bin\Release\nl.buddypayment.apps.buddy-Signed.aab --mode=universal --output=D:\a\1\s\extract.apks --ks=D:\a\_temp\apk_signing_keystore.jks --ks-pass=pass:*** --ks-key-alias=upload --key-pass=pass:*** --overwrite
java.lang.UnsupportedClassVersionError: com/android/tools/build/bundletool/BundleToolMain has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
Error: A JNI error has occurred, please check your installation and try again
```

I expect many pipelines around the world to be broken now.
Would be nice to either revert this release or to add "upgrade" instructions at least.

**Bundletool version(s) affected**
Version: [1.12.0](https://github.com/google/bundletool/releases/tag/1.12.0) [Latest](https://github.com/google/bundletool/releases/latest)

**Environment:**
OS: `windows-latest` - https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md

**Comment by ymakhno** [comment]
Fixed in 1.12.1.
