### ISSUE TITLE
Inject signature mode of adding code transparency fails with incompatible version of bundletool dex

### ISSUE THREAD

**Issue by raghuraamms** [google/bundletool#304]
Version of bundletool : 1.12.1

Issue faced:

[BT:1.12.1] Error: Not found the appropriate version of DEX file for bundletool version: 1.8.0
java.lang.IllegalStateException: Not found the appropriate version of DEX file for bundletool version: 1.8.0
        at com.google.common.base.Preconditions.checkState(Preconditions.java:590)
        at com.android.tools.build.bundletool.archive.ArchivedResourcesHelper.getArchivedClassesDexPath(ArchivedResourcesHelper.java:118)
        at com.android.tools.build.bundletool.archive.ArchivedResourcesHelper.getArchivedClassesDexPath(ArchivedResourcesHelper.java:90)
        at com.android.tools.build.bundletool.transparency.CodeTransparencyFactory.createArchivedCodeRelatedFile(CodeTransparencyFactory.java:72)
        at com.android.tools.build.bundletool.transparency.CodeTransparencyFactory.createCodeTransparencyMetadata(CodeTransparencyFactory.java:57)
        at com.android.tools.build.bundletool.transparency.BundleTransparencyCheckUtils.getCodeRelatedFilesFromBundle(BundleTransparencyCheckUtils.java:130)
        at com.android.tools.build.bundletool.transparency.BundleTransparencyCheckUtils.checkTransparency(BundleTransparencyCheckUtils.java:101)
        at com.android.tools.build.bundletool.transparency.BundleTransparencyCheckUtils.checkTransparency(BundleTransparencyCheckUtils.java:71)
        at com.android.tools.build.bundletool.commands.AddTransparencyCommand.executeInjectSignatureMode(AddTransparencyCommand.java:368)
        at com.android.tools.build.bundletool.commands.AddTransparencyCommand.execute(AddTransparencyCommand.java:285)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:126)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:54)

Steps to reproduce:

1. Generate code transparency file with bundletool
2. Get the file signed externally and get the signature binary
3. Try to inject the signature binary into bundletool as documented in the docs: https://developer.android.com/guide/app-bundle/code-transparency#add-bundletool

E:> java -jar "C:\Users\raghurr\Downloads\bundletool-all-1.12.1.jar" add-transparency --mode=inject_signature --bundle="officemobilebundle.aab" --output=test.aab  --transparency-key-certificate="mod.cer" --transparency-signature="application.sig" --allow-shared-user-id

The command fails with the above error.

The tool works if we run the add-transparency option while providing the keystore so it seems to be an issue only with running the inject signature mode separately.

Let me know if you need additional details or help reproducing the issue.

**Comment by ymakhno** [comment]
The workaround is to update bundletool which is used to build aab file to 1.8.2 or above.

**Comment by ymakhno** [comment]
Fixed in 1.13.0.
