### ISSUE TITLE
Error: Version must match the format '<major>.<minor>.<revision>[-<qualifier>]', but found '0.0.0/'

### ISSUE THREAD

**Issue by littledog623** [google/bundletool#331]
Version of bundle: 1.15.0

[BT:1.15.0] Error: Version must match the format '<major>.<minor>.<revision>[-<qualifier>]', but found '0.0.0/'.
java.lang.IllegalArgumentException: Version must match the format '<major>.<minor>.<revision>[-<qualifier>]', but found '0.0.0/'.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220)
	at com.android.tools.build.bundletool.model.version.Version.of(Version.java:67)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at com.android.tools.build.bundletool.archive.ArchivedResourcesHelper.findArchivedClassesDexPath(ArchivedResourcesHelper.java:105)
	at com.android.tools.build.bundletool.transparency.CodeTransparencyFactory.createArchivedCodeRelatedFile(CodeTransparencyFactory.java:72)
	at com.android.tools.build.bundletool.transparency.CodeTransparencyFactory.createCodeTransparencyMetadata(CodeTransparencyFactory.java:56)
	at com.android.tools.build.bundletool.commands.AddTransparencyCommand.executeGenerateCodeTransparencyFileMode(AddTransparencyCommand.java:341)
	at com.android.tools.build.bundletool.commands.AddTransparencyCommand.execute(AddTransparencyCommand.java:282)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:138)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:55)

I cannot repro this locally, but I am able to repro this on Azure Devops pipeline. I suspect that this is caused by some weird behavior of the Windows pipeline agent that I am using. 

Can we add some extra logic to normalize the path to the dex resource files?

**Comment by ymakhno** [comment]
Thank you for the PR I'm fine to merge it but as I see it is still in draft. Did it solve your problem or not?
