### ISSUE TITLE
aapt2 binary failed to execute on the ARM64 Node 

### ISSUE THREAD

**Issue by Chandru0211** [google/bundletool#333]
aapt2 binary failed to execute on the ARM64 arch linux VM. 

we are using bundletool-all-1.7.0.jar and the execution failing with below error.

[BT:1.15.0] Error: Command '[/tmp/AutoValue_BuildApksCommand16124706071610713255/output/linux/aapt2, convert, --output-format, binary, -o, /tmp/3084128052921734964/binary2.apk, /tmp/3084128052921734964/proto1.apk]' didn't terminate successfully (exit code: 2). Check the logs.
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Command '[/tmp/AutoValue_BuildApksCommand16124706071610713255/output/linux/aapt2, convert, --output-format, binary, -o, /tmp/3084128052921734964/binary2.apk, /tmp/3084128052921734964/proto1.apk]' didn't terminate successfully (exit code: 2). Check the logs.
	at com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57)
	at com.android.tools.build.bundletool.androidtools.DefaultCommandExecutor.executeImpl(DefaultCommandExecutor.java:57)
	at com.android.tools.build.bundletool.androidtools.DefaultCommandExecutor.execute(DefaultCommandExecutor.java:33)
	at com.android.tools.build.bundletool.androidtools.Aapt2Command$1.convertApkProtoToBinary(Aapt2Command.java:71)
	at com.android.tools.build.bundletool.io.Aapt2ResourceConverter$ResourceConverter.convertAndOptimizeProtoApk(Aapt2ResourceConverter.java:158)
	at com.android.tools.build.bundletool.io.Aapt2ResourceConverter$ResourceConverter.convertResourcesToBinary(Aapt2ResourceConverter.java:125)
	at com.android.tools.build.bundletool.io.Aapt2ResourceConverter.lambda$convert$3(Aapt2ResourceConverter.java:105)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
{"log.timestamp":"2023-05-26 05:14:48.288","log.class_name":"com.onetrust.appscan.service.impl.AndroidDecompileImpl","log.level":"ERROR","log.application":"mobile-appscan","log.trace_id":"374c81fb8e8705a7","log.spanid":"6fc7b9f591654f9a","log.user_id":"0071e2e6-04c1-4f9c-be96-ef831fa0aebe","log.tenant_id":"16026","log.tenant_guid":"af6aa20c-54ea-4ae1-97e8-068e906702da","log.origin_module":"(none)","log.thread_id":"12","log.thread_name":"engineThreadPoolTaskExecutor-1","log.message":"ExecutionException caught in execute java.util.concurrent.ExecutionException: com.onetrust.appscan.exception.ApkDecompileException: Exception during decompile "}
java.util.concurrent.ExecutionException: com.onetrust.appscan.exception.ApkDecompileException: Exception during decompile
	at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.onetrust.appscan.service.impl.AndroidDecompileImpl.execute(AndroidDecompileImpl.java:102)
	at com.onetrust.appscan.service.impl.AndroidDecompileImpl.getApkFromAab(AndroidDecompileImpl.java:215)
	at com.onetrust.appscan.service.impl.AndroidDecompileImpl.decompileAab(AndroidDecompileImpl.java:74)
	at com.onetrust.appscan.service.impl.AndroidDecompileImpl.decompile(AndroidDecompileImpl.java:43)
	at com.onetrust.appscan.service.impl.AndroidDecompileImpl$$FastClassBySpringCGLIB$$1a04cb59.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at io.sentry.spring.tracing.SentrySpanAdvice.invoke(SentrySpanAdvice.java:36)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at com.onetrust.appscan.service.impl.AndroidDecompileImpl$$EnhancerBySpringCGLIB$$deab2a8c.decompile(<generated>)
	at com.onetrust.appscan.service.impl.AndroidScanEngineImpl.doScan(AndroidScanEngineImpl.java:39)
	at com.onetrust.appscan.service.impl.AndroidScanEngineImpl$$FastClassBySpringCGLIB$$2fa39738.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at io.sentry.spring.tracing.SentrySpanAdvice.invoke(SentrySpanAdvice.java:36)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at com.onetrust.appscan.service.impl.AndroidScanEngineImpl$$EnhancerBySpringCGLIB$$fc1a7189.doScan(<generated>)
	at com.onetrust.appscan.service.impl.ScanServiceImpl.startScan(ScanServiceImpl.java:62)
	at com.onetrust.appscan.service.impl.ScanServiceImpl$$FastClassBySpringCGLIB$$fa82e442.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at io.sentry.spring.tracing.SentrySpanAdvice.invoke(SentrySpanAdvice.java:36)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at com.onetrust.appscan.service.impl.ScanServiceImpl$$EnhancerBySpringCGLIB$$2c43cee7.startScan(<generated>)
	at com.onetrust.appscan.task.AppScanTask.call(AppScanTask.java:42)
	at com.onetrust.appscan.task.AppScanTask.call(AppScanTask.java:17)
	at org.springframework.cloud.sleuth.instrument.async.TraceCallable.call(TraceCallable.java:67)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.onetrust.appscan.exception.ApkDecompileException: Exception during decompile
	at com.onetrust.appscan.service.impl.AndroidDecompileImpl$PrintResultHandler.onProcessFailed(AndroidDecompileImpl.java:169)
	at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:203)
	... 1 more
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48)
	at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200)
	... 1 more

do we have support for arm64 arch for aapt2 binary ?

**Comment by VijaySHegde** [comment]
+1

**Comment by hanchao1986** [comment]
+1

**Comment by ymakhno** [comment]
Closing this as this is not a bundletool issue. There is no official aapt2 build for ARM64, you may follow this bug: https://issuetracker.google.com/issues/227219818 for updates.

If you end up using alternative one you can just specify path to aapt2 binary via `--aapt2` flag.
