### ISSUE TITLE
 Error: Module 'myzip' is missing mandatory file 'manifest/AndroidManifest.xml'

### ISSUE THREAD

**Issue by raj-paw** [google/bundletool#337]
**Describe the bug**
When I am using java jar bundletool command I am getting below error but when I am trying bundletool command without including java jar keyword I am not getting error and also not generating the ".aab" file. Could you please help me to resolve this issue.

**Bundletool version(s) affected**
Version: [e.g. 0.3.3]

**Stacktrace**
Copy all of the output of the command, including the stacktrace if visible.

C:\IMS\Android App>java -jar bundletool.jar build-bundle --modules=myzip.zip --output=base.aab
[BT:1.15.1] Error: Module 'myzip' is missing mandatory file 'manifest/AndroidManifest.xml'.
com.android.tools.build.bundletool.model.exceptions.InvalidBundleException: Module 'myzip' is missing mandatory file 'manifest/AndroidManifest.xml'.
        at com.android.tools.build.bundletool.model.exceptions.UserExceptionBuilder.build(UserExceptionBuilder.java:58)
        at com.android.tools.build.bundletool.validation.MandatoryFilesPresenceValidator.checkModuleHasAndroidManifest(MandatoryFilesPresenceValidator.java:88)
        at com.android.tools.build.bundletool.validation.MandatoryFilesPresenceValidator.validateModuleZipFile(MandatoryFilesPresenceValidator.java:43)
        at com.android.tools.build.bundletool.validation.ValidatorRunner.lambda$validateModuleZipFile$2(ValidatorRunner.java:54)
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
        at com.android.tools.build.bundletool.validation.ValidatorRunner.validateModuleZipFile(ValidatorRunner.java:54)
        at com.android.tools.build.bundletool.validation.BundleModulesValidator.validate(BundleModulesValidator.java:72)
        at com.android.tools.build.bundletool.commands.BuildBundleCommand.execute(BuildBundleCommand.java:231)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:79)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:55)

C:\IMS\Android App>bundletool.jar build-bundle --modules=myzip.zip --output=base.aab

C:\IMS\Android App>

**To Reproduce**
Steps to reproduce the behavior.
Include the full command being run as well as, if possible, artifacts the bug can be reproduced with.

**Expected behavior**

**Known workaround**
If you have found a workaround, please specify what it is.

**Environment:**
OS: [e.g. iOS 10.3.3]

**Additional context**

**Comment by ffdsss** [comment]
Have you solved it

**Comment by ymakhno** [comment]
This is a problem with your input (myzip module) and error is self descriptive. Not a bundletool issue.
