### ISSUE TITLE
[BUG] Error: Module 'base' is missing mandatory file 'manifest/AndroidManifest.xml'.

### ISSUE THREAD

**Issue by ffdsss** [google/bundletool#339]
**Describe the bug**
 java -jar bundletool-all-1.14.1.jar build-bundle --modules=base.zip --output=base.aab
[BT:1.14.1] Error: Module 'base' is missing mandatory file 'manifest/AndroidManifest.xml'.
com.android.tools.build.bundletool.model.exceptions.InvalidBundleException: Module 'base' is missing mandatory file 'manifest/AndroidManifest.xml'.
        at com.android.tools.build.bundletool.model.exceptions.UserExceptionBuilder.build(UserExceptionBuilder.java:58)
        at com.android.tools.build.bundletool.validation.MandatoryFilesPresenceValidator.checkModuleHasAndroidManifest(MandatoryFilesPresenceValidator.java:88)
        at com.android.tools.build.bundletool.validation.MandatoryFilesPresenceValidator.validateModuleZipFile(MandatoryFilesPresenceValidator.java:43)
        at com.android.tools.build.bundletool.validation.ValidatorRunner.lambda$validateModuleZipFile$2(ValidatorRunner.java:54)
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
        at com.android.tools.build.bundletool.validation.ValidatorRunner.validateModuleZipFile(ValidatorRunner.java:54)
        at com.android.tools.build.bundletool.validation.BundleModulesValidator.validate(BundleModulesValidator.java:72)
        at com.android.tools.build.bundletool.commands.BuildBundleCommand.execute(BuildBundleCommand.java:231)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:79)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:55)

**Bundletool version(s) affected**
Version: [1.15.1]

**Stacktrace**
Copy all of the output of the command, including the stacktrace if visible.

**To Reproduce**
Steps to reproduce the behavior.
Include the full command being run as well as, if possible, artifacts the bug can be reproduced with.

**Expected behavior**

**Known workaround**
If you have found a workaround, please specify what it is.

**Environment:**
OS: [windows11]

**Additional context**
![image](https://github.com/google/bundletool/assets/48895716/b9562796-157c-4a53-b3c4-b199bb2d596d)

**Comment by ymakhno** [comment]
This is not bundletool issue as mandatory file is missing in your base.zip.
