### ISSUE TITLE
 com.android.tools.build.bundletool.model.exceptions.InvalidBundleException: Invalid dex file indices, expecting file 'classes?.dex' but found 'classes2.dex'.

### ISSUE THREAD

**Issue by slugger941** [google/bundletool#344]
**Describe the bug**
 com.android.tools.build.bundletool.model.exceptions.InvalidBundleException: Invalid dex file indices, expecting file 'classes?.dex' but found 'classes2.dex'.
	at com.android.tools.build.bundletool.model.exceptions.UserExceptionBuilder.build(UserExceptionBuilder.java:58)
	at com.android.tools.build.bundletool.validation.DexFilesValidator.validateDexNames(DexFilesValidator.java:78)
	at com.android.tools.build.bundletool.validation.DexFilesValidator.validateModule(DexFilesValidator.java:63)
	at com.android.tools.build.bundletool.validation.ValidatorRunner.validateBundleModulesUsingSubValidator(ValidatorRunner.java:100)
	at com.android.tools.build.bundletool.validation.ValidatorRunner.lambda$validateBundleModules$6(ValidatorRunner.java:75)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at com.android.tools.build.bundletool.validation.ValidatorRunner.validateBundleModules(ValidatorRunner.java:74)
	at com.android.tools.build.bundletool.validation.BundleModulesValidator.validate(BundleModulesValidator.java:79)
	at com.android.tools.build.bundletool.commands.BuildBundleCommand.execute(BuildBundleCommand.java:231)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:78)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:54)

**Bundletool version(s) affected**
Version: 1.13.2

**Stacktrace**
 com.android.tools.build.bundletool.model.exceptions.InvalidBundleException: Invalid dex file indices, expecting file 'classes?.dex' but found 'classes2.dex'.
	at com.android.tools.build.bundletool.model.exceptions.UserExceptionBuilder.build(UserExceptionBuilder.java:58)
	at com.android.tools.build.bundletool.validation.DexFilesValidator.validateDexNames(DexFilesValidator.java:78)
	at com.android.tools.build.bundletool.validation.DexFilesValidator.validateModule(DexFilesValidator.java:63)
	at com.android.tools.build.bundletool.validation.ValidatorRunner.validateBundleModulesUsingSubValidator(ValidatorRunner.java:100)
	at com.android.tools.build.bundletool.validation.ValidatorRunner.lambda$validateBundleModules$6(ValidatorRunner.java:75)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at com.android.tools.build.bundletool.validation.ValidatorRunner.validateBundleModules(ValidatorRunner.java:74)
	at com.android.tools.build.bundletool.validation.BundleModulesValidator.validate(BundleModulesValidator.java:79)
	at com.android.tools.build.bundletool.commands.BuildBundleCommand.execute(BuildBundleCommand.java:231)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:78)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:54)

**To Reproduce**
Steps to reproduce the behavior.
java -jar bundletool-all-1.13.2.jar build-bundle --output=xxx.aab

**Expected behavior**
not occured error

**Known workaround**

**Environment:**
OS: window 11, Language : Arab

**Additional context**

**Comment by ymakhno** [comment]
Your module zip file contains dex files with wrong name. Not a bundletool issue.

**Comment by tangligen1995** [comment]
"C:\Program Files\Java\jdk1.8.0_361\bin\java.exe" -jar bundletool-all-1.14.0.jar build-bundle --modules=base.zip --output=base.aab
[BT:1.14.0] Error: Files under dex/ must match the 'classes[0-9]*.dex' pattern, found 'dex/classes_.dex'.
com.android.tools.build.bundletool.model.exceptions.InvalidBundleException: Files under dex/ must match the 'classes[0-9]*.dex' pattern, found 'dex/classes_.dex'.
        at com.android.tools.build.bundletool.model.exceptions.UserExceptionBuilder.build(UserExceptionBuilder.java:58)
        at com.android.tools.build.bundletool.validation.BundleFilesValidator.validateModuleFile(BundleFilesValidator.java:79)
        at com.android.tools.build.bundletool.validation.ValidatorRunner.validateBundleModulesUsingSubValidator(ValidatorRunner.java:103)
        at com.android.tools.build.bundletool.validation.ValidatorRunner.lambda$validateBundleModules$6(ValidatorRunner.java:75)
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
        at com.android.tools.build.bundletool.validation.ValidatorRunner.validateBundleModules(ValidatorRunner.java:74)
        at com.android.tools.build.bundletool.validation.BundleModulesValidator.validate(BundleModulesValidator.java:79)
        at com.android.tools.build.bundletool.commands.BuildBundleCommand.execute(BuildBundleCommand.java:231)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:79)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:55)
