### ISSUE TITLE
Installation of the app failed

### ISSUE THREAD

**Issue by hujiachun** [google/bundletool#36]
**Describe the bug**
When execute the install comand，for example：
java  -jar bundletoo.jar  install-apks --apks=test.apks --device-id  LHTDU16927053257

In effect，the app install success,but Tip me “Error: Installation of the app failed.” on the console。
I can find the app package for the device。

**Bundletool version(s) affected**
Version: [release 0.7.1]

**Stacktrace**
The APKs have been extracted in the directory: /tmp/temp644958597244074835
[BT:0.7.1] Error: Installation of the app failed.
com.android.tools.build.bundletool.exceptions.InstallationException: Installation of the app failed.
	at com.android.tools.build.bundletool.exceptions.InstallationException$Builder.build(InstallationException.java:47)
	at com.android.tools.build.bundletool.exceptions.InstallationException$Builder.build(InstallationException.java:41)
	at com.android.tools.build.bundletool.device.DdmlibDevice.installApks(DdmlibDevice.java:122)
	at com.android.tools.build.bundletool.device.ApksInstaller.installOnDevice(ApksInstaller.java:94)
	at com.android.tools.build.bundletool.device.ApksInstaller.installApks(ApksInstaller.java:82)
	at com.android.tools.build.bundletool.device.ApksInstaller.installApks(ApksInstaller.java:62)
	at com.android.tools.build.bundletool.commands.InstallApksCommand.lambda$execute$3(InstallApksCommand.java:166)
	at com.android.tools.build.bundletool.io.TempFiles.lambda$withTempDirectory$0(TempFiles.java:68)
	at com.android.tools.build.bundletool.io.TempFiles.withTempDirectoryReturning(TempFiles.java:52)
	at com.android.tools.build.bundletool.io.TempFiles.withTempDirectory(TempFiles.java:71)
	at com.android.tools.build.bundletool.commands.InstallApksCommand.execute(InstallApksCommand.java:146)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:91)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:47)
Caused by: com.android.ddmlib.InstallException
	at com.android.ddmlib.SplitApkInstaller.install(SplitApkInstaller.java:100)
	at com.android.ddmlib.Device.installPackages(Device.java:928)
	at com.android.tools.build.bundletool.device.DdmlibDevice.installApks(DdmlibDevice.java:106)
	... 10 more
Caused by: com.android.ddmlib.ShellCommandUnresponsiveException
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:557)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:383)
	at com.android.ddmlib.Device.executeShellCommand(Device.java:575)
	at com.android.ddmlib.SplitApkInstaller.install(SplitApkInstaller.java:86)
	... 12 more

**Comment by ymakhno** [comment]
`install-apks` command provided is correct. ShellCommandUnresponsiveException says that device is not responsive.
