### ISSUE TITLE
failed to install universall.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl296733659.tmp/base.apk using APK Signature Scheme v3: integer overflow]

### ISSUE THREAD

**Issue by huangjunkun** [google/bundletool#378]
java -jar bundletool-all-1.17.2.jar build-apks --bundle=s11_1206.aab --mode=universal --output=s11/s11.apks --ks=... 

adb install universall.apk

 failed to install universall.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl296733659.tmp/base.apk using APK Signature Scheme v3: integer overflow]

2024-12-06 11:25:29.503  1895-2054  PackageInstallerSession pid-1895                             I  onSessionValidationFailure: Failed collecting certificates for /data/app/vmdl580168889.tmp/PackageInstaller
                                                                                                    android.content.pm.PackageParser$PackageParserException: Failed to collect certificates from /data/app/vmdl580168889.tmp/PackageInstaller using APK Signature Scheme v3
                                                                                                    	at android.util.apk.ApkSignatureVerifier.verifyV3Signature(ApkSignatureVerifier.java:311)
                                                                                                    	at android.util.apk.ApkSignatureVerifier.verifyV3AndBelowSignatures(ApkSignatureVerifier.java:144)
                                                                                                    	at android.util.apk.ApkSignatureVerifier.verifySignaturesInternal(ApkSignatureVerifier.java:136)
                                                                                                    	at android.util.apk.ApkSignatureVerifier.verifySignatures(ApkSignatureVerifier.java:96)
                                                                                                    	at android.util.apk.ApkSignatureVerifier.verify(ApkSignatureVerifier.java:71)
                                                                                                    	at android.content.pm.parsing.ParsingPackageUtils.getSigningDetails(ParsingPackageUtils.java:3641)
                                                                                                    	at android.content.pm.parsing.ApkLiteParseUtils.parseApkLiteInner(ApkLiteParseUtils.java:373)
                                                                                                    	at android.content.pm.parsing.ApkLiteParseUtils.parseApkLite(ApkLiteParseUtils.java:329)
                                                                                                    	at com.android.server.pm.PackageInstallerSession.validateApkInstallLocked(PackageInstallerSession.java:3203)
                                                                                                    	at com.android.server.pm.PackageInstallerSession.streamValidateAndCommit(PackageInstallerSession.java:2172)
                                                                                                    	at com.android.server.pm.PackageInstallerSession.handleStreamValidateAndCommit(PackageInstallerSession.java:1847)
                                                                                                    	at com.android.server.pm.PackageInstallerSession.access$2000(PackageInstallerSession.java:195)
                                                                                                    	at com.android.server.pm.PackageInstallerSession$4.handleMessage(PackageInstallerSession.java:916)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:113)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:293)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:110)
                                                                                                    Caused by: java.lang.ArithmeticException: integer overflow
                                                                                                    	at java.lang.Math.toIntExact(Math.java:1061)
                                                                                                    	at android.util.apk.VerityBuilder.generateApkVerityDigestAtLeafLevel(VerityBuilder.java:333)
                                                                                                    	at android.util.apk.VerityBuilder.generateVerityTreeInternal(VerityBuilder.java:392)
                                                                                                    	at android.util.apk.VerityBuilder.generateVerityTreeInternal(VerityBuilder.java:102)
                                                                                                    	at android.util.apk.VerityBuilder.generateApkVerityTree(VerityBuilder.java:84)
                                                                                                    	at android.util.apk.ApkSigningBlockUtils.verifyIntegrityForVerityBasedAlgorithm(ApkSigningBlockUtils.java:372)
                                                                                                    	at android.util.apk.ApkSigningBlockUtils.verifyIntegrity(ApkSigningBlockUtils.java:128)
                                                                                                    	at android.util.apk.ApkSignatureSchemeV3Verifier.verify(ApkSignatureSchemeV3Verifier.java:207)
                                                                                                    	at android.util.apk.ApkSignatureSchemeV3Verifier.verify(ApkSignatureSchemeV3Verifier.java:137)
                                                                                                    	at android.util.apk.ApkSignatureSchemeV3Verifier.verify(ApkSignatureSchemeV3Verifier.java:120)
                                                                                                    	at android.util.apk.ApkSignatureSchemeV3Verifier.verify(ApkSignatureSchemeV3Verifier.java:100)
                                                                                                    	at android.util.apk.ApkSignatureVerifier.verifyV3Signature(ApkSignatureVerifier.java:290)
                                                                                                    	at android.util.apk.ApkSignatureVerifier.verifyV3AndBelowSignatures(ApkSignatureVerifier.java:144)Â 
                                                                                                    	at android.util.apk.ApkSignatureVerifier.verifySignaturesInternal(ApkSignatureVerifier.java:136)Â 
                                                                                                    	at android.util.apk.ApkSignatureVerifier.verifySignatures(ApkSignatureVerifier.java:96)Â 
                                                                                                    	at android.util.apk.ApkSignatureVerifier.verify(ApkSignatureVerifier.java:71)Â 
                                                                                                    	at android.content.pm.parsing.ParsingPackageUtils.getSigningDetails(ParsingPackageUtils.java:3641)Â 
                                                                                                    	at android.content.pm.parsing.ApkLiteParseUtils.parseApkLiteInner(ApkLiteParseUtils.java:373)Â 
                                                                                                    	at android.content.pm.parsing.ApkLiteParseUtils.parseApkLite(ApkLiteParseUtils.java:329)Â 
                                                                                                    	at com.android.server.pm.PackageInstallerSession.validateApkInstallLocked(PackageInstallerSession.java:3203)Â 
                                                                                                    	at com.android.server.pm.PackageInstallerSession.streamValidateAndCommit(PackageInstallerSession.java:2172)Â 
                                                                                                    	at com.android.server.pm.PackageInstallerSession.handleStreamValidateAndCommit(PackageInstallerSession.java:1847)Â 
                                                                                                    	at com.android.server.pm.PackageInstallerSession.access$2000(PackageInstallerSession.java:195)Â 
                                                                                                    	at com.android.server.pm.PackageInstallerSession$4.handleMessage(PackageInstallerSession.java:916)Â 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:113)Â 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)Â 
                                                                                                    	at android.os.Looper.loop(Looper.java:293)Â 
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:110)Â 

Supplement：
s11_1206.aab  package size exceeds 3G

**Comment by huangjunkun** [comment]
Supplement：
s11_1206.aab  package size exceeds 3G

**Comment by namnq-sipher** [comment]
I met this issue too and haven't found a solution yet.

**Comment by huangjunkun** [comment]
@namnq-sipher  You can use Android apksigner to resgin apk, when the size  of apk exceeds 2G. 
I have already done this before, you can refer to it.

**Comment by namnq-sipher** [comment]
> [@namnq-sipher](https://github.com/namnq-sipher) emmmm this is BUG. You can use Android apksigner to resgin apk, when the size of apk exceeds 2G. I have already done this before, you can refer to it.

thanks for the info @huangjunkun. After resigning the APK using `apksigner`, I can install the APK without this error. My app size is larger than 2GB indeed.

**Comment by Avalix** [comment]
Any update on this - I have this issue with builds that upload fine to google play, but bundle tool fails with this error.

Or is there more details on the workaround above and how to sign the apk files inside the .apks?

**Comment by SmileKeith** [comment]
I encountered the same issue with an AAB that was only 1.88 GB, so it wasn't actually over the 2 GiB limit. Re-signing the exact same AAB resolved the problem immediately.
