### ISSUE TITLE
location of ADB

### ISSUE THREAD

**Issue by lu769257351** [google/bundletool#44]
我执行安装是出现这个错误，在Windows环境下
```
java -jar F:\tool\bundletool\bundletool.jar install-apks --apks=F:\tool\bundletool\app.apks
[BT:0.7.2] Error: Unable to determine the location of ADB. Please set the --adb flag or define ANDROID_HOME environment variable.
com.android.tools.build.bundletool.exceptions.CommandExecutionException: Unable to determine the location of ADB. Please set the --adb flag or define ANDROID_HOME environment variable.
        at com.android.tools.build.bundletool.commands.InstallApksCommand.lambda$null$1(InstallApksCommand.java:117)
        at java.util.Optional.orElseThrow(Unknown Source)
        at com.android.tools.build.bundletool.commands.InstallApksCommand.lambda$fromFlags$2(InstallApksCommand.java:115)
        at java.util.Optional.orElseGet(Unknown Source)
        at com.android.tools.build.bundletool.commands.InstallApksCommand.fromFlags(InstallApksCommand.java:110)
        at com.android.tools.build.bundletool.commands.InstallApksCommand.fromFlags(InstallApksCommand.java:99)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:91)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:47)
```

**Comment by plecesne** [comment]
The error message explains what is wrong and how to fix it: `Please set the --adb flag or define ANDROID_HOME environment variable.`

You can either provide the `--adb` flag on the command line with the path to the `adb` binary, or define the `ANDROID_HOME` environment variable with the path to the Android SDK.

**Comment by lu769257351** [comment]
@plecesne  谢谢，这个问题我已经解决了，是我的环境有问题

**Comment by LiuPangYao** [comment]
請問環境有哪些地方需要調整
