### ISSUE TITLE
bundletool get-size throws ValidationException

### ISSUE THREAD

**Issue by OscarSpruit** [google/bundletool#71]
When I run `bundletool get-size apks=<path to .apks file>` I get the following exception:

```
Error: Target of the get-size command not found.
com.android.tools.build.bundletool.model.exceptions.ValidationException: Target of the get-size command not found.
	at com.android.tools.build.bundletool.commands.GetSizeCommand.lambda$parseGetSizeSubCommand$0(GetSizeCommand.java:195)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at com.android.tools.build.bundletool.commands.GetSizeCommand.parseGetSizeSubCommand(GetSizeCommand.java:194)
	at com.android.tools.build.bundletool.commands.GetSizeCommand.fromFlags(GetSizeCommand.java:175)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:98)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:46)

```
I'm not sure what the error means, but what I do know is that the path to the .apks file is right.

Bundletool version: 0.9.0
OS: macOS Mojave 10.14.4

**Comment by plecesne** [comment]
If you run

    $ bundletool help get-size

it will give you the proper syntax of the command:

```
Synopsis:
    bundletool get-size total
        --apks=<archive.apks>
        [--device-spec=<device-spec.json>]
        [--dimensions=<SDK,ABI,SCREEN_DENSITY,LANGUAGE,ALL>]
        [--instant]
        [--modules=<base,module1,module2>]
```

You're missing the `total` keyword.
