### ISSUE TITLE
The 'base' module is missing from the resource table, but contains resource files.

### ISSUE THREAD

**Issue by dsocardoso** [google/bundletool#72]
Hi,

I attempted to send the aab application to Google Play, but I received an error when bundletool runs, showing: The 'base' module is missing from the resource table, but contains resource files.

Can you help me?

**Comment by plecesne** [comment]
How did you build the AAB? It looks invalid based on the error message.

**Comment by dsocardoso** [comment]
Hi @plecesne  

I've build the app in jenkins CI.  We've made the changes following the bundle specifications  in Google article.  
It's possible to obtain bundletool logs to understand what is the problem with aab? 
What does mean The base module is missing from resource table?  Can you show me more details?

Thanks,

**Comment by plecesne** [comment]
Jenkins does not actually build the AAB, it just schedules operations. Can you confirm that you use Gradle to build the AAB?

The error message is not "is missing from resource table" but "is missing [a] resource table". You have resources (i.e. files under "base/res/") but not resource table (i.e. "base/resources.pb"). The resource table is generated automatically by Gradle when you have resources.

Do you have maybe JAR dependencies to your project that contain files under "res"? That could possibly explain the issue.

**Comment by dsocardoso** [comment]
Hi @plecesne 
I use gradle to build the AAB and jenkins to schedules operations. That's correct. 
The project has some jar files.  For example, we use dexguard to obfuscate the source code application.  This is a problem? 
Is there way to find in the project what could be the problem?  Can i use log or bundletool offers logging to understand what happens when splits the aab into apks ? 

Here's the trace with the problem when i tried to use the bundletool: 

`com.android.tools.build.bundletool.model.exceptions.ResouceTableException$ResourceTableMissingException: Module 'base' is missing resource table but contains resource files.
	at com.android.tools.build.bundletool.validation.ResourceTableValidator.validateModule(ResourceTableValidator.java:61)
	at com.android.tools.build.bundletool.validation.ValidatorRunner.validateBundleModulesUsingSubValidator(ValidatorRunner.java:78)
	at com.android.tools.build.bundletool.validation.ValidatorRunner.validateBundleUsingSubValidator(ValidatorRunner.java:69)
	at com.android.tools.build.bundletool.validation.ValidatorRunner.lambda$validateBundle$3(ValidatorRunner.java:58)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:406)
	at com.android.tools.build.bundletool.validation.ValidatorRunner.validateBundle(ValidatorRunner.java:58)
	at com.android.tools.build.bundletool.validation.AppBundleValidator.validate(AppBundleValidator.java:74)
	at com.android.tools.build.bundletool.commands.BuildApksManager.execute(BuildApksManager.java:93)
	at com.android.tools.build.bundletool.commands.BuildApksCommand.execute(BuildApksCommand.java:486)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:74)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:46)`


Thanks,

**Comment by plecesne** [comment]
Are you using a recent version of dexguard? I know there were some issues at the beginning where they didn't have proper support for App Bundles but fixed it shortly after.

**Comment by dsocardoso** [comment]
Yes, we're using versions that offers support to bundle.  (Dexguard v8.3 / 8.4) 
@plecesne  There is a way to activate log to understand what occurs when using bundletool or when is compiling the aab who indicates the problem?

**Comment by plecesne** [comment]
Bundletool only looks at the files in the AAB and sees that there are files under "base/res/" but no "base/resources.pb" file, that's all there is to know.

Can you try and disable Dexguard to see if that fixes the issue? If so, the issue probably lays in Dexguard.

**Comment by plecesne** [comment]
Is your issue resolved?

**Comment by dsocardoso** [comment]
Yes. The problem occurs because the use of dexguard. Thanks.
