### ISSUE TITLE
Cannot fit requested classes in the main-dex file.

### ISSUE THREAD

**Issue by JingYeoh** [google/bundletool#74]
**Describe the bug**
Cannot fit requested classes in the main-dex file. when dynamic feature module contains dex.
>Don't merge if all dex files live inside a single module. If that module contains multiple
 dex files, it should have been built with multi-dex support.

why the multi-dex will be merged in here. [ModuleSplitsToShardMerger](https://github.com/google/bundletool/blob/master/src/main/java/com/android/tools/build/bundletool/mergers/ModuleSplitsToShardMerger.java#L282)

**Bundletool version(s) affected**
Version: 0.9.0

**Stacktrace**
```
# methods: 199616 > 65536 ; # fields: 117536 > 65536
[BT:0.9.0] Error: Dex merging failed.
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Dex merging failed.
	at com.android.tools.build.bundletool.mergers.D8DexMerger.translateD8Exception(D8DexMerger.java:98)
	at com.android.tools.build.bundletool.mergers.D8DexMerger.merge(D8DexMerger.java:77)
	at com.android.tools.build.bundletool.mergers.ModuleSplitsToShardMerger.mergeDexFiles(ModuleSplitsToShardMerger.java:334)
	at com.android.tools.build.bundletool.mergers.ModuleSplitsToShardMerger.lambda$mergeDexFilesAndCache$3(ModuleSplitsToShardMerger.java:301)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1126)
	at com.android.tools.build.bundletool.mergers.ModuleSplitsToShardMerger.mergeDexFilesAndCache(ModuleSplitsToShardMerger.java:299)
	at com.android.tools.build.bundletool.mergers.ModuleSplitsToShardMerger.mergeSingleShard(ModuleSplitsToShardMerger.java:192)
	at com.android.tools.build.bundletool.mergers.ModuleSplitsToShardMerger.merge(ModuleSplitsToShardMerger.java:106)
	at com.android.tools.build.bundletool.splitters.BundleSharder.shardBundle(BundleSharder.java:102)
	at com.android.tools.build.bundletool.splitters.ShardedApksGenerator.generateSplits(ShardedApksGenerator.java:68)
	at com.android.tools.build.bundletool.commands.BuildApksManager.execute(BuildApksManager.java:187)
	at com.android.tools.build.bundletool.commands.BuildApksCommand.execute(BuildApksCommand.java:486)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:74)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:46)
	at com.android.tools.build.bundletool.BundleToolMainTest.test(BundleToolMainTest.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:76)
	at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:45)
	at com.android.tools.r8.D8.run(D8.java:67)
	at com.android.tools.build.bundletool.mergers.D8DexMerger.merge(D8DexMerger.java:70)
	... 38 more
Caused by: com.android.tools.r8.utils.AbortException
	at com.android.tools.r8.utils.Reporter.failIfPendingErrors(Reporter.java:77)
	at com.android.tools.r8.utils.Reporter.fatalError(Reporter.java:67)
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:62)
	... 41 more
	Suppressed: com.android.tools.r8.errors.DexOverflowException: Cannot fit requested classes in the main-dex file (# methods: 199616 > 65536 ; # fields: 117536 > 65536)
		at com.android.tools.r8.dex.VirtualFile.throwIfFull(VirtualFile.java:182)
		at com.android.tools.r8.dex.VirtualFile$DistributorBase.fillForMainDexList(VirtualFile.java:305)
		at com.android.tools.r8.dex.VirtualFile$FillFilesDistributor.run(VirtualFile.java:353)
		at com.android.tools.r8.dex.ApplicationWriter.distribute(ApplicationWriter.java:144)
		at com.android.tools.r8.dex.ApplicationWriter.write(ApplicationWriter.java:164)
		at com.android.tools.r8.D8.run(D8.java:167)
		at com.android.tools.r8.D8.lambda$run$0(D8.java:71)
		at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:58)
		... 41 more
```

**Comment by kvafy** [comment]
This is expected bundletool behavior.

There are two possible causes - either your bundle is missing the main dex list file, or the main dex list is present but too long. Please check your bundle for file `BUNDLE-METADATA/com.android.tools.build.bundletool/mainDexList.txt`. Make sure to use the latest Android Gradle plug-in.
Alternatively, in case you don't want the dynamic feature module included in APKs for pre-Lollipop devices, you can exclude the module from those APKs in which case bundletool won't attempt to merge the dex files. This can be configured via `<dist:fusing include="false"/>` [attribute](https://developer.android.com/studio/projects/dynamic-delivery#create_dynamic_feature) in the AndroidManifest.xml of the feature module.
