### ISSUE TITLE
[BT:0.9.0] Error: File '' is a directory. java.lang.IllegalArgumentException: File '' is a directory

### ISSUE THREAD

**Issue by chihung93** [google/bundletool#77]
**Describe the bug**
I try do build-apks from android app bundle but I get an error.
I have already try to use 2 versions: 0.3.3 and 0.9.0 but these libs don't work.
I had to use `sudo` for making sure these libs have full access/permission to run the command line.
I had to create 2 folders which have the name `output.apks` and `output`. But nothing work

`sudo java -jar bundletool-all-0.9.0.jar build-apks --bundle=app.aab --output=output.apks  --ks --ks-key-alias`

**Bundletool version(s) affected**
Version: 0.3.3 & 0.9.0

**Stacktrace**
```
[BT:0.9.0] Error: File '' is a directory.
java.lang.IllegalArgumentException: File '' is a directory.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:204)
	at com.android.tools.build.bundletool.model.utils.files.FilePreconditions.checkFileExistsAndReadable(FilePreconditions.java:36)
	at com.android.tools.build.bundletool.model.SigningConfiguration.extractFromKeystore(SigningConfiguration.java:86)
	at com.android.tools.build.bundletool.commands.BuildApksCommand.fromFlags(BuildApksCommand.java:414)
	at com.android.tools.build.bundletool.commands.BuildApksCommand.fromFlags(BuildApksCommand.java:374)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:74)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:46)

```

**To Reproduce**
1. Download libs: 0.9.0 or 0.3.3
2. Run `sudo java -jar bundletool-all-0.9.0.jar build-apks --bundle=app.aab --output=output.apks  --ks --ks-key-alias`

**Expected behavior**
Generate APKs

**Known workaround**
If you have found a workaround, please specify what it is.

**Environment:**
OS: MacOS 10.14.2 Beta (18C52a)

**Additional context**
![My Folder](https://i.imgur.com/T3LiDDv.png)
![My Command Line](https://i.imgur.com/gPMsDqM.png)

**Comment by plecesne** [comment]
This will be fixed in the next release. In the meantime, you can use a full path for the output, i.e. `--output=/Users/X/test/output.apks`

**Comment by chihung93** [comment]
`--output=/Users/X/test/output.apks ` => not working, I have to create a folder's name `output.apks`
![my command line](https://i.imgur.com/FTzwepw.png)

**Comment by plecesne** [comment]
It looks like you haven't provided any value to the flags `--ks` and `--ks-key-alias`.

**Comment by chihung93** [comment]
@plecesne :
I added these flag ` --ks=keystore --ks-pass=pass:{myKeystorePassword} --ks-key-alias={alias} --key-pass=pass:{myKeystorePassword}` => its work

But I have other issues If I have created folder `output.apks`

[BT:0.9.0] Error: File '/Users/{user}/Desktop/test/outputs.apks' already exists.
java.lang.IllegalArgumentException: File '/Users/{user}/Desktop/test/outputs.apks' already exists.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:204)
	at com.android.tools.build.bundletool.model.utils.files.FilePreconditions.checkFileDoesNotExist(FilePreconditions.java:29)
	at com.android.tools.build.bundletool.commands.BuildApksManager.validateInput(BuildApksManager.java:358)
	at com.android.tools.build.bundletool.commands.BuildApksManager.execute(BuildApksManager.java:77)
	at com.android.tools.build.bundletool.commands.BuildApksCommand.execute(BuildApksCommand.java:486)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:74)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:46)

```

**Comment by plecesne** [comment]
As the error message mentions, the output file already exists. Delete it, or add the flag `--overwrite` to the command if you want to overwrite it.

You can find the list of flags in the help:

```
bundletool help build-apks
```
