### ISSUE TITLE
Unexpected output of 'pm list features' command

### ISSUE THREAD

**Issue by sampalmer** [google/bundletool#81]
**Describe the bug**
Crash when using `install-apks` on Android 4.4.2

**Bundletool version(s) affected**
Version: 0.9.0

**Stacktrace**

    PS C:\Users\sam__\Desktop> java -jar C:\Utilities\bundletool\bundletool-all-0.9.0.jar install-apks --apks=64.apks
    [BT:0.9.0] Error: Unexpected output of 'pm list features' command: 'WARNING: linker: libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.'
    com.android.tools.build.bundletool.model.exceptions.ParseException: Unexpected output of 'pm list features' command: 'WARNING: linker: libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.'
            at com.android.tools.build.bundletool.model.exceptions.ParseException$Builder.build(ParseException.java:49)
            at com.android.tools.build.bundletool.model.exceptions.ParseException$Builder.build(ParseException.java:41)
            at com.android.tools.build.bundletool.device.DeviceFeaturesParser.parse(DeviceFeaturesParser.java:38)
            at com.android.tools.build.bundletool.device.DdmlibDevice.getDeviceFeatures(DdmlibDevice.java:83)
            at com.android.tools.build.bundletool.device.DeviceAnalyzer.getDeviceSpec(DeviceAnalyzer.java:60)
            at com.android.tools.build.bundletool.commands.InstallApksCommand.execute(InstallApksCommand.java:145)
            at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:88)
            at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:46)

**To Reproduce**
1. Start the Android emulator for *Google APIs Intel x86 Atom System Image* for API Level 19 and Revision 38
2. Run `java -jar bundletool-all-0.9.0.jar install-apks --apks=64.apks` using [the attached APKs](https://github.com/google/bundletool/files/3292627/64.zip)

**Expected behavior**
App installed onto emulator successfully

**Environment:**
OS: Android 4.4.2

**Comment by plecesne** [comment]
Thanks for reporting this issue. No exception should be thrown indeed, but note that this reveals an issue in your app as well (`WARNING: linker: libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.'`) which you should consider addressing.

**Comment by sampalmer** [comment]
> this reveals an issue in your app as well

In this case, I believe the error is related to the system image itself. Even when my app is not installed on the device, running `adb shell pm list features` still produces the `libdvm.so has text relocations` warning.

**Comment by startthread** [comment]
I am getting same error on version `0.10.0` while installing on API 19 emulator.

Per discussion above, it is just  warning `WARNING: linker: libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.` when we run `adb shell pm list features`, but with `bundletool` it is Error and doesn't allow us to continue. 

Is there any other version we can use meanwhile?

**Comment by plecesne** [comment]
Fixed in 0.10.1.
