### ISSUE TITLE
NPE while attempting to generate device spec

### ISSUE THREAD

**Issue by paddyzab** [google/bundletool#85]
**Describe the bug**
Generation of device-spec throws NPE.

**Bundletool version(s) affected**
Version: 0.10.0

**Stacktrace**
```
[BT:0.10.0] Error: null
java.lang.NullPointerException
	at java.nio.file.Files.provider(Files.java:97)
	at java.nio.file.Files.exists(Files.java:2385)
	at com.android.tools.build.bundletool.commands.GetDeviceSpecCommand.writeDeviceSpecToFile(GetDeviceSpecCommand.java:175)
	at com.android.tools.build.bundletool.commands.GetDeviceSpecCommand.execute(GetDeviceSpecCommand.java:164)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:83)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:46)
```
**To Reproduce**
Here we have small problem since it's a common task which probably works for many. 
Here is the command:
`bundletool get-device-spec --output=device_h9.json`

**Expected behavior**
Lack of NPE, the device spec json file is created.

**Known workaround**
Providing the full path to the file, correctly generates the spec.

**Environment:**
OS: MacOS Mojave 10.14.5

**Comment by kvafy** [comment]
Thank you for the bug report. There seems to be a bug in resolution of paths that contain the file name as the only path component. As a workaround, you can specify an absolute path in the `--output` parameter.

**Comment by madz0** [comment]
I get the same exception with 
`java -jar /absolute/path/to/bundletool-all-0.10.0.jar install-apks --apks=/home/user/Desktop/xxx.apks`

The result is:

```
The APKs have been extracted in the directory: /tmp/9187462177714548095
[BT:0.10.0] Error: null
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787)
	at com.google.common.base.Joiner.toString(Joiner.java:454)
	at com.google.common.base.Joiner.appendTo(Joiner.java:106)
	at com.google.common.base.Joiner.appendTo(Joiner.java:154)
	at com.google.common.base.Joiner.join(Joiner.java:197)
	at com.google.common.base.Joiner.join(Joiner.java:187)
	at com.google.common.base.Joiner.join(Joiner.java:205)
	at com.android.ddmlib.Device.installRemotePackage(Device.java:1024)
	at com.android.ddmlib.Device.installPackage(Device.java:902)
	at com.android.ddmlib.Device.installPackage(Device.java:880)
	at com.android.ddmlib.Device.installPackage(Device.java:869)
	at com.android.tools.build.bundletool.device.DdmlibDevice.installApks(DdmlibDevice.java:113)
	at com.android.tools.build.bundletool.device.ApksInstaller.installOnDevice(ApksInstaller.java:94)
	at com.android.tools.build.bundletool.device.ApksInstaller.installApks(ApksInstaller.java:82)
	at com.android.tools.build.bundletool.device.ApksInstaller.installApks(ApksInstaller.java:44)
	at com.android.tools.build.bundletool.commands.InstallApksCommand.execute(InstallApksCommand.java:165)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:88)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:46)
```

**Comment by kvafy** [comment]
@madz0, these two null pointer exceptions are unrelated. Can you please open a separate issue?

**Comment by madz0** [comment]
@kvafy You're right. I'll submit an issue

**Comment by simeonlam** [comment]
@paddyzab This error is related to output path parent folder not found
You should run as `bundletool get-device-spec --output=./device_h9.json`

**Comment by paddyzab** [comment]
> @paddyzab This error is related to output path parent folder not found
> You should run as `bundletool get-device-spec --output=./device_h9.json`

Thanks man, 

@kvafy (your call if you want to keep it open) workaround works as expected.
As a user what I would expect is to create the file in the current directory.

**Comment by kvafy** [comment]
The next bundletool release will contain a fix. We'll close the bug then. Thanks everyone!
